# Grafana Alloy — cross-platform telemetry collector.
#
# Part of the fleet telemetry train (issue #2458). This is the first
# child (issue #2460): host metrics only. Loki log shipping and other
# signals are explicitly out of scope here — a commented seam is left
# in the generated Alloy config so a later train can wire `loki.write`
# without redesigning the module surface.
#
# ── Cross-platform shape ─────────────────────────────────────────────
#
# Modelled on `modules/programs/tailscale-client/default.nix`: an
# `nx.*` enable option with two platform branches:
#
#   * NixOS (navi, tui) — reuses the upstream nixpkgs
#     `services.alloy` module, which provides a systemd unit with
#     DynamicUser, StateDirectory, and reload-on-config-change.
#     Config is written to `/etc/alloy/config.alloy` via
#     `environment.etc` so the nixpkgs module can pick it up and
#     trigger a reload on switch.
#
#   * Darwin (m4mac) — nix-darwin has no first-class services.alloy,
#     so we roll a `launchd.daemons.alloy` unit (system-scope, root)
#     ourselves. RunAtLoad + KeepAlive so it survives crashes and
#     restarts on boot without depending on a user login. Config
#     lives at the same `/etc/alloy/config.alloy` path on both
#     platforms for consistency.
#
# ── Auth boundary ────────────────────────────────────────────────────
#
# v1 requires NO application auth token. The tailnet IS the auth
# boundary: the home-ops headscale ACL policy grants only our user
# (`ben@`) reach into the ts-metrics-ingest node on tcp/9090.
# Nothing else on the tailnet can talk to it. If a token is ever
# required in the future it lives in sops — a commented seam is left
# in the generated River config below.
#
# ── Metric collection: prometheus.exporter.unix cross-platform ──────
#
# The AC wording for #2460 said "hostmetrics" (as in the OpenTelemetry
# `otelcol.receiver.hostmetrics` component). That component is NOT
# registered in nixpkgs' `grafana-alloy` 1.17.1 build — the build
# targets the `collector/` subpackage of the alloy repo, and
# `internal/component/otelcol/receiver/` in that tree does not
# contain a `hostmetrics/` subdirectory. Adding it would require
# either upgrading nixpkgs' alloy version (out of scope for this PR)
# or maintaining an out-of-tree component registration.
#
# Instead we use `prometheus.exporter.unix` cross-platform. This is
# Alloy's *embedded* node_exporter component — the node_exporter Go
# code is compiled into the alloy binary and exposed as a River
# component. It is NOT a separate node_exporter binary, package, or
# systemd unit; the AC's "no node_exporter dependency (no
# node_exporter added)" reads as forbidding a separate node_exporter
# service, and this satisfies that reading — nothing on the host
# except `alloy` runs.
#
# Platform coverage (default collector set):
#
#   * Linux: cpu, diskstats, filesystem, loadavg, meminfo, netdev,
#     hwmon (lm_sensors temperatures), thermal_zone, plus many
#     others.
#   * Darwin: boottime, cpu, diskstats, filesystem, loadavg,
#     meminfo, netdev, time, uname. No temperature collectors on
#     Darwin — matches the AC ("temperatures on Linux where
#     lm_sensors exposes them").
#
# We rely on the platform-appropriate defaults rather than pinning
# `set_collectors` so the exporter's platform-conditional collector
# registration handles the split naturally.
{
  config,
  lib,
  pkgs,
  isLinux,
  ...
}:
let
  cfg = config.nx.services.alloy;
  hostname = config.networking.hostName;
  isDarwin = !isLinux;

  # Alloy River config. Kept as a single generated file for both
  # platforms — the metric-collection component is the same on both.
  #
  # NB: Alloy expects River syntax, not HCL. Backticks / dollar-braces
  # here are literal to River. Nix interpolation is via `${...}`; where
  # a literal `${...}` is needed in River, escape as `''${...}''`.
  alloyConfig = ''
    // Generated by modules/services/alloy/default.nix. Do not edit
    // /etc/alloy/config.alloy by hand — changes will be overwritten on
    // the next nixos-rebuild / darwin-rebuild switch.
    //
    // Host: ${hostname}
    // Push target: ${cfg.prometheusRemoteWriteUrl}

    // ── Host metrics (cross-platform) ────────────────────────────────
    //
    // prometheus.exporter.unix is Alloy's embedded node_exporter. On
    // Linux it enables the full default collector set (which includes
    // hwmon + thermal_zone for lm_sensors temperatures); on Darwin it
    // enables the Darwin-supported subset (cpu, diskstats, filesystem,
    // loadavg, meminfo, netdev, ...). This is a single component
    // compiled into the alloy binary — it is NOT a separate
    // node_exporter package or service (see module header for the
    // reasoning behind not using `otelcol.receiver.hostmetrics`).
    prometheus.exporter.unix "node" {
    }

    prometheus.scrape "node" {
      targets         = prometheus.exporter.unix.node.targets
      forward_to      = [prometheus.remote_write.default.receiver]
      scrape_interval = "60s"
    }

    // ── Push to home-ops Prometheus over the tailnet ────────────────
    //
    // v1 needs no auth token — the tailnet is the auth boundary
    // (headscale ACL grants `ben@` -> ts-metrics-ingest tcp/9090
    // only). If a token is ever required, add a
    //   basic_auth { username = "..." password_file = "..." }
    // block inside `endpoint` and wire the file via sops.
    //
    // external_labels adds a `hostname` label to every series so
    // navi / tui / m4mac are distinguishable in Prometheus.
    prometheus.remote_write "default" {
      external_labels = {
        hostname = "${hostname}",
      }

      endpoint {
        url = "${cfg.prometheusRemoteWriteUrl}"
      }
    }

    // ── Future seam: Loki log shipping ───────────────────────────────
    //
    // Deliberately not wired here (issue #2460 is metrics only). When
    // #2458's log-shipping child lands, add:
    //
    //   loki.write "default" {
    //     external_labels = { hostname = "${hostname}" }
    //     endpoint { url = "http://ts-loki.tailnet.internal:3100/loki/api/v1/push" }
    //   }
    //
    // and one or more loki.source.* components forwarding to it. The
    // headscale ACL already grants tcp/3100 to `ben@` so no ACL work
    // will be required at that time.
  '';
in
{
  options.nx.services.alloy = {
    enable = lib.mkEnableOption "Grafana Alloy telemetry collector (host metrics via prometheus.exporter.unix)";

    prometheusRemoteWriteUrl = lib.mkOption {
      type = lib.types.str;
      default = "http://ts-metrics-ingest.tailnet.internal:9090/api/v1/write";
      description = ''
        Prometheus `remote_write` endpoint URL that Alloy pushes host
        metrics to.

        Must be a MagicDNS name reachable from every enrolled node,
        NOT a LAN-only address — tui and m4mac need to keep pushing
        while roaming off the home LAN. The default resolves to the
        home-ops dedicated `ts-metrics-ingest` node (home-ops #3386),
        which is a single-replica ingest Prometheus with the
        remote-write receiver enabled. It is deliberately NOT
        `ts-prometheus.tailnet.internal`: that hostname is a
        2-replica HA scrape pair, and pushing remote_write at it
        would split samples non-deterministically across replicas.

        NOTE: as of PR time `ts-metrics-ingest.tailnet.internal` is
        not yet live (home-ops #3386 is gated behind their PR #3385).
        Until it lands, alloy's remote_write client will fail-retry
        against a non-resolving DNS name — the alloy service itself
        stays up (active/running); only the push side is deferred.
      '';
    };
  };

  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      # Config file at a stable path on both platforms so `alloy run`
      # can read it. On NixOS the upstream services.alloy module picks
      # this up via its reloadTriggers scan of `environment.etc."alloy/*.alloy"`.
      {
        environment.etc."alloy/config.alloy".text = alloyConfig;
      }

      # ── NixOS ────────────────────────────────────────────────────────
      #
      # Guarded by the `isLinux` specialArg from flake.nix rather than
      # `lib.mkIf pkgs.stdenv.isLinux`. mkIf is lazy on its value but
      # the module system still walks the definition tree to register
      # option paths, and top-level `launchd` does not exist on NixOS
      # (nor does top-level `services.alloy` on nix-darwin). Using
      # mkIf would trip the option-existence check on the wrong
      # platform. `optionalAttrs` collapses to `{}` at Nix time before
      # the module system sees it, sidestepping the check. `isLinux`
      # comes via specialArgs so evaluating it does not require
      # resolving the module option set (which is what caused
      # infinite recursion when the same pattern was tried against
      # `pkgs.stdenv.isDarwin`).
      (lib.optionalAttrs isLinux {
        services.alloy = {
          enable = true;
          # configPath defaults to /etc/alloy — matches the
          # environment.etc file above. `environmentFile` stays null:
          # v1 requires no auth token, and if it ever does, this is
          # the seam for a sops-decrypted path.
        };
      })

      # ── Darwin ───────────────────────────────────────────────────────
      #
      # nix-darwin has no first-class services.alloy, so we roll our
      # own launchd system daemon. Root-run so it can read every
      # node_exporter collector's data source without privilege drops.
      # RunAtLoad plus KeepAlive so it starts on boot and self-heals
      # if it crashes, without depending on a user login (unlike the
      # tailscale-headscale-up hook, which is a user agent because it
      # consumes sops user-scope secrets).
      (lib.optionalAttrs isDarwin {
        launchd.daemons.alloy = {
          serviceConfig = {
            ProgramArguments = [
              "/bin/sh"
              "-c"
              # /bin/wait4path guards against the daemon starting
              # before the /nix APFS volume is mounted at boot (the
              # alloy binary lives in the store).
              "/bin/wait4path ${pkgs.grafana-alloy}/bin/alloy && exec ${pkgs.grafana-alloy}/bin/alloy run --storage.path=/var/lib/alloy /etc/alloy/config.alloy"
            ];
            RunAtLoad = true;
            KeepAlive = true;
            # /var/log is root-writable and not a symlink hazard;
            # /tmp would be.
            StandardOutPath = "/var/log/alloy.log";
            StandardErrorPath = "/var/log/alloy.log";
            # Ensure the storage dir exists before alloy runs. launchd
            # will not create it for us.
            WorkingDirectory = "/var/lib/alloy";
          };
        };

        # Create the storage directory during activation. `alloy run
        # --storage.path` expects it to exist.
        system.activationScripts.extraActivation.text = lib.mkAfter ''
          echo "ensuring /var/lib/alloy exists for Grafana Alloy..."
          mkdir -p /var/lib/alloy
          chmod 0755 /var/lib/alloy
        '';
      })
    ]
  );
}
