// Package config — profiles.go
//
// Loads model profiles from ~/.config/prism/profiles.json and generates
// the OPENCODE_CONFIG_CONTENT JSON blob that overrides opencode's runtime
// model and variant configuration at precedence level 6 (highest).
//
// As of #1206 the profile schema is role-keyed: each profile is a map from
// session role (coordinator, worker, plan, explore, review-goal, ...) to a
// per-role configuration record carrying provider, model, thinking, and
// systemPromptPath. The legacy {primary, secondary, lightweight} bucket
// model is no longer the source of truth — it survives only as
// `role_mapping`, a tier classification used by the override semantics
// (`--model` alongside `--profile` overrides only the primary tier).
//
// The profiles.json file is generated by Nix and has this shape:
//
//	{
//	  "default": "anthropic",
//	  "role_mapping": {
//	    "primary":     ["coordinator", "plan"],
//	    "secondary":   ["worker", "review", "review-goal", ...],
//	    "lightweight": ["explore", "title", "summary", "compaction"]
//	  },
//	  "profiles": {
//	    "anthropic": {
//	      "coordinator": {"provider":"anthropic","model":"anthropic/claude-sonnet-4-6","thinking":"none","systemPromptPath":""},
//	      "plan":        {"provider":"anthropic","model":"anthropic/claude-sonnet-4-6","thinking":"none","systemPromptPath":""},
//	      "worker":      {"provider":"anthropic","model":"anthropic/claude-sonnet-4-6","thinking":"none","systemPromptPath":""},
//	      ...
//	      "explore":     {"provider":"anthropic","model":"anthropic/claude-haiku-4-5","thinking":"none","systemPromptPath":""}
//	    },
//	    "anthropic-opus": {...},
//	    "gemini-hybrid":  {...}
//	  }
//	}
//
// OPENCODE_CONFIG_CONTENT semantics (preserved from the pre-#1206 schema):
//   - The top-level "model" is set to the coordinator slot's model.
//   - Each agent in role_mapping gets its own "agent.<name>.model" entry
//     drawn from the slot of the same name.
//   - "agent.<name>.variant" carries the slot's `thinking` value. It is
//     emitted only when non-empty so that absent thinking levels do not
//     interfere with opencode's default variant resolution.

package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RoleSlot is the per-role configuration record introduced by #1206.
//
// Field semantics:
//   - Provider: routing provider name (consumed by P2.AGENTRUN; unused today
//     for opencode rendering).
//   - Model: model identifier emitted into opencode.json.
//   - Thinking: reasoning level. Rendered as opencode's `variant` to
//     preserve bit-identical output with the pre-#1206 schema.
//   - SystemPromptPath: optional absolute path to a per-role system prompt
//     (consumed by P2.AGENTRUN; not surfaced in the legacy opencode shim).
type RoleSlot struct {
	Provider         string `json:"provider,omitempty"`
	Model            string `json:"model"`
	Thinking         string `json:"thinking,omitempty"`
	SystemPromptPath string `json:"systemPromptPath,omitempty"`
}

// ProfileEntry maps session role names ("coordinator", "worker", "plan",
// "explore", "review-goal", ...) to their per-role slot configs.
//
// Under the role-keyed schema (#1206) each role is a first-class slot. The
// legacy {primary, secondary, lightweight} bucket lookup has moved into
// `role_mapping`, which classifies roles into tiers but no longer carries
// model values directly.
type ProfileEntry map[string]RoleSlot

// ProfilesFile is the on-disk structure of profiles.json.
type ProfilesFile struct {
	Default     string                  `json:"default"`
	RoleMapping map[string][]string     `json:"role_mapping"`
	Profiles    map[string]ProfileEntry `json:"profiles"`
	// ContainerWorkerConfig is the full opencode.json blob (serialised JSON
	// string) to inject as OPENCODE_CONFIG_CONTENT for worker containers.
	// Written by Nix under container_worker_config.
	ContainerWorkerConfig string `json:"container_worker_config"`
	// ContainerCoordinatorConfig is the full opencode.json blob (serialised
	// JSON string) to inject as OPENCODE_CONFIG_CONTENT for coordinator
	// containers. Written by Nix under container_coordinator_config.
	ContainerCoordinatorConfig string `json:"container_coordinator_config"`
	// Per-agent review container configs — each blob declares only its own
	// review agent and no others. Written by Nix under
	// container_review_{goal,code,security,qa,context}_config.
	// Each blob is hardened: write/edit/patch denied; task tool disabled;
	// "prism review" bash commands denied to prevent recursion.
	ContainerReviewGoalConfig     string `json:"container_review_goal_config"`
	ContainerReviewCodeConfig     string `json:"container_review_code_config"`
	ContainerReviewSecurityConfig string `json:"container_review_security_config"`
	ContainerReviewQaConfig       string `json:"container_review_qa_config"`
	ContainerReviewContextConfig  string `json:"container_review_context_config"`
	// AgentEnvVars holds environment variables to inject into host-mode
	// opencode processes. Values are fully expanded absolute paths (no $HOME).
	// Written by Nix under agent_env_vars. These are prepended to the
	// opencode command string in buildDirectOpencodeCmd so that sh -c
	// sessions (which do not load .zshrc or zsh aliases) receive them.
	AgentEnvVars map[string]string `json:"agent_env_vars,omitempty"`
	// ContainerResources holds per-container resource cap values to be passed
	// to podman run as --memory, --memory-swap, and --pids-limit.
	// Written by Nix under container_resources.
	ContainerResources ContainerResources `json:"container_resources,omitempty"`
	// QuickProfiles holds lightweight model configs for prism quick subcommands.
	// Written by Nix under quick_profiles.
	QuickProfiles map[string]QuickProfile `json:"quick_profiles,omitempty"`
}

// ContainerResources holds the per-container resource cap values that are
// passed to podman run via buildRunArgs. Zero values / empty strings mean
// "no flag emitted" so that callers not running via the nix module are
// not affected.
type ContainerResources struct {
	// MemoryMax is the value for podman run --memory (e.g. "8g").
	// Empty string means no --memory flag.
	MemoryMax string `json:"memoryMax,omitempty"`
	// MemorySwapMax is the value for podman run --memory-swap (e.g. "8g").
	// Empty string means no --memory-swap flag.
	MemorySwapMax string `json:"memorySwapMax,omitempty"`
	// PidsLimit is the value for podman run --pids-limit.
	// Zero means no --pids-limit flag.
	PidsLimit int `json:"pidsLimit,omitempty"`
}

// QuickProfile holds the model and provider routing config for a prism quick
// subcommand (e.g. "pr"). Written by Nix under quick_profiles.<name>.
type QuickProfile struct {
	// Model is the OpenRouter model slug (e.g. "google/gemini-3.1-flash-lite-preview").
	Model string `json:"model"`
	// ProviderOrder is the ordered list of OpenRouter provider slugs to try
	// (e.g. ["google", "google-vertex"]). Maps to provider.order in the API request.
	ProviderOrder []string `json:"providerOrder,omitempty"`
}

// ContainerConfigForRole returns the OPENCODE_CONFIG_CONTENT blob for the
// given agent role. Returns ("", nil) when pf is nil (no profiles file loaded)
// or when the role is not a recognised container role.
//
// Recognised roles:
//   - "worker"           → ContainerWorkerConfig
//   - "coordinator"      → ContainerCoordinatorConfig
//   - "review-goal"      → ContainerReviewGoalConfig
//   - "review-code"      → ContainerReviewCodeConfig
//   - "review-security"  → ContainerReviewSecurityConfig
//   - "review-qa"        → ContainerReviewQaConfig
//   - "review-context"   → ContainerReviewContextConfig
//
// The old "review" role (from PR-A) is retired. Calling it returns ("", nil).
// Subagent names like "plan", "explore", etc. also return ("", nil) — they
// inherit from the session default.
func ContainerConfigForRole(pf *ProfilesFile, role string) (string, error) {
	if pf == nil {
		return "", nil
	}
	switch role {
	case "worker":
		return pf.ContainerWorkerConfig, nil
	case "coordinator":
		return pf.ContainerCoordinatorConfig, nil
	case "review-goal":
		return pf.ContainerReviewGoalConfig, nil
	case "review-code":
		return pf.ContainerReviewCodeConfig, nil
	case "review-security":
		return pf.ContainerReviewSecurityConfig, nil
	case "review-qa":
		return pf.ContainerReviewQaConfig, nil
	case "review-context":
		return pf.ContainerReviewContextConfig, nil
	default:
		// Not a container-level role (e.g. "plan", "explore", or the retired "review").
		// Return empty string — no config injection — without error.
		return "", nil
	}
}

// profilesFilePath returns the path to profiles.json.
// Returns "" if no home directory is discoverable.
func profilesFilePath() string {
	configHome := os.Getenv("XDG_CONFIG_HOME")
	if configHome == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return ""
		}
		configHome = filepath.Join(home, ".config")
	}
	return filepath.Join(configHome, "prism", "profiles.json")
}

// LoadProfiles reads and parses the profiles.json file.
// Returns a descriptive error if the file is missing, unreadable, or malformed.
func LoadProfiles() (*ProfilesFile, error) {
	path := profilesFilePath()
	if path == "" {
		return nil, fmt.Errorf("profiles: cannot determine profiles.json path (no home directory)")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("profiles: %s not found — run the system rebuild to generate it", path)
		}
		return nil, fmt.Errorf("profiles: read %s: %w", path, err)
	}
	var pf ProfilesFile
	if err := json.Unmarshal(data, &pf); err != nil {
		return nil, fmt.Errorf("profiles: parse %s: %w", path, err)
	}
	return &pf, nil
}

// AvailableProfileNames returns a sorted list of profile names defined in pf.
func AvailableProfileNames(pf *ProfilesFile) []string {
	names := make([]string, 0, len(pf.Profiles))
	for name := range pf.Profiles {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// SlotForRole returns the slot configured for the given role in the named
// profile. It is the canonical role-keyed lookup introduced by #1206.
//
// Returns (RoleSlot{}, false) when pf is nil, the profile is unknown, or the
// profile defines no slot for that role.
func SlotForRole(pf *ProfilesFile, profileName, role string) (RoleSlot, bool) {
	if pf == nil {
		return RoleSlot{}, false
	}
	entry, ok := pf.Profiles[profileName]
	if !ok {
		return RoleSlot{}, false
	}
	slot, ok := entry[role]
	return slot, ok
}

// RequireSlot validates that the named profile defines a slot for the given
// session role. It returns nil when the slot is present, or a descriptive
// error listing every role the active profile currently defines so the
// caller can see the gap at a glance.
//
// This is the spawn-time edge-case gate from #1206: a session whose role
// cannot be resolved against the active profile must fail early with a clear
// diagnostic rather than silently falling through to the top-level default.
func RequireSlot(pf *ProfilesFile, profileName, role string) error {
	if pf == nil {
		return fmt.Errorf("profiles: profile %q requires slot %q but profiles file not loaded", profileName, role)
	}
	entry, ok := pf.Profiles[profileName]
	if !ok {
		return fmt.Errorf("profiles: unknown profile %q — available: %s",
			profileName, strings.Join(AvailableProfileNames(pf), ", "))
	}
	if _, ok := entry[role]; ok {
		return nil
	}
	defined := make([]string, 0, len(entry))
	for name := range entry {
		defined = append(defined, name)
	}
	sort.Strings(defined)
	return fmt.Errorf(
		"profiles: profile %q does not define a slot for session role %q — defined slots: %s",
		profileName, role, strings.Join(defined, ", "),
	)
}

// LegacyOpencodeConfigFor renders the role-keyed profile into the
// OPENCODE_CONFIG_CONTENT JSON shape opencode expects:
//
//	{
//	  "model": "<coordinator model>",
//	  "agent": {
//	    "<role>": {"model": "...", "variant": "..."},
//	    ...
//	  }
//	}
//
// It is the compatibility shim from #1206 — opencode's external surface
// (`opencode.json`) is unchanged; internally `BuildConfigContent` consumes
// the new schema via this shim. Tests can also call it directly to assert
// bit-identical output across the migration.
//
// Returns ("", nil) when pf is nil. Returns an error when the named profile
// is not present.
func LegacyOpencodeConfigFor(pf *ProfilesFile, profileName string) (string, error) {
	if pf == nil {
		return "", nil
	}
	entry, ok := pf.Profiles[profileName]
	if !ok {
		return "", fmt.Errorf("profiles: unknown profile %q — available: %s",
			profileName, strings.Join(AvailableProfileNames(pf), ", "))
	}

	agentMap := make(map[string]agentCfg)

	// Choose the top-level model. Prefer the coordinator slot — that has
	// always been the primary-tier model in practice — and fall back to the
	// first primary-tier role from role_mapping when coordinator is missing.
	topModel := ""
	if slot, ok := entry["coordinator"]; ok {
		topModel = slot.Model
	} else {
		for _, name := range pf.RoleMapping["primary"] {
			if slot, ok := entry[name]; ok {
				topModel = slot.Model
				break
			}
		}
	}

	// Per-agent map: every role in role_mapping that has a slot in the
	// profile contributes one entry. Preserves the pre-#1206 semantics of
	// "every agent listed in role_mapping receives an agent.<name> entry".
	for _, names := range pf.RoleMapping {
		for _, name := range names {
			slot, ok := entry[name]
			if !ok {
				continue
			}
			agentMap[name] = agentCfg{
				model:   slot.Model,
				variant: variantFromThinking(slot.Thinking),
			}
		}
	}

	return marshalConfigContent(topModel, agentMap)
}

// agentCfg holds the model and variant for a single opencode agent.
type agentCfg struct {
	model   string
	variant string
}

// variantFromThinking maps a slot's `thinking` value to opencode's `variant`
// field. The two are aliases — the schema redesign in #1206 renamed the
// concept but kept the wire format identical so that opencode sessions
// produce bit-identical output across the migration.
//
// An empty thinking value is rendered as an empty variant (which
// marshalConfigContent then omits from the output entirely).
func variantFromThinking(thinking string) string {
	return thinking
}

// BuildConfigContent generates the OPENCODE_CONFIG_CONTENT JSON string for the
// given spawn options.
//
// Rules:
//   - If profileName is non-empty, load that profile and apply it.
//   - If modelOverride is non-empty (without a profile), set top-level model
//     and all agent models to modelOverride.
//   - If modelOverride is set alongside profileName, it overrides top-level
//     model AND the primary-role agents only; secondary/lightweight agents
//     retain profile values.
//   - If variantOverride is non-empty, set "variant" on ALL agent configs.
//   - Returns ("", nil) when no flags are set (no injection needed).
//
// pf may be nil when no profile flag is used; it is only consulted when
// profileName is non-empty.
func BuildConfigContent(pf *ProfilesFile, profileName, modelOverride, variantOverride string) (string, error) {
	if profileName == "" && modelOverride == "" && variantOverride == "" {
		return "", nil
	}

	// agentMap accumulates per-agent configs keyed by agent name.
	agentMap := make(map[string]agentCfg)
	topModel := ""

	if profileName != "" {
		if pf == nil {
			return "", fmt.Errorf("profiles: profile %q requested but profiles file not loaded", profileName)
		}
		entry, ok := pf.Profiles[profileName]
		if !ok {
			available := AvailableProfileNames(pf)
			return "", fmt.Errorf("profiles: unknown profile %q — available: %s",
				profileName, strings.Join(available, ", "))
		}

		// Top-level model: coordinator slot when present, falling back to the
		// first primary-tier role from role_mapping. This mirrors the legacy
		// rule (`entry["primary"].Model`) under the role-keyed schema where
		// coordinator/plan share the primary tier.
		if slot, ok := entry["coordinator"]; ok {
			topModel = slot.Model
		} else {
			for _, name := range pf.RoleMapping["primary"] {
				if slot, ok := entry[name]; ok {
					topModel = slot.Model
					break
				}
			}
		}

		// Per-agent map: each role in role_mapping with a slot in the
		// profile contributes its slot's model + thinking → variant.
		for _, names := range pf.RoleMapping {
			for _, name := range names {
				slot, ok := entry[name]
				if !ok {
					continue
				}
				agentMap[name] = agentCfg{
					model:   slot.Model,
					variant: variantFromThinking(slot.Thinking),
				}
			}
		}
	}

	// Apply modelOverride.
	if modelOverride != "" {
		topModel = modelOverride
		if profileName != "" {
			// Only override primary-role agents.
			if pf != nil {
				for _, agentName := range pf.RoleMapping["primary"] {
					ac := agentMap[agentName]
					ac.model = modelOverride
					agentMap[agentName] = ac
				}
			}
		} else {
			// No profile: override all agents.
			// We need the full agent list. Use a known hardcoded default set
			// since we may not have a profiles file.
			allAgents := allKnownAgents(pf)
			for _, agentName := range allAgents {
				ac := agentMap[agentName]
				ac.model = modelOverride
				agentMap[agentName] = ac
			}
		}
	}

	// Apply variantOverride.
	if variantOverride != "" {
		// Collect all agents we know about.
		allAgents := allKnownAgents(pf)
		for _, agentName := range allAgents {
			ac := agentMap[agentName]
			ac.variant = variantOverride
			agentMap[agentName] = ac
		}
	}

	// If neither profile nor model was set we still have topModel = "".
	// Don't emit top-level "model" key when it's empty.
	// Build the JSON structure.
	return marshalConfigContent(topModel, agentMap)
}

// allKnownAgents returns all agent names known from the profiles file's role
// mapping, or a hardcoded fallback set when pf is nil.
func allKnownAgents(pf *ProfilesFile) []string {
	if pf != nil {
		seen := make(map[string]struct{})
		var agents []string
		for _, roleAgents := range pf.RoleMapping {
			for _, a := range roleAgents {
				if _, ok := seen[a]; !ok {
					seen[a] = struct{}{}
					agents = append(agents, a)
				}
			}
		}
		sort.Strings(agents)
		return agents
	}
	// Hardcoded fallback: the standard set of opencode agents prism uses.
	return []string{
		"ac",
		"compaction",
		"coordinator",
		"explore",
		"plan",
		"review",
		"summary",
		"title",
		"worker",
	}
}

// ApplyModelOverrides patches modelOverride and/or variantOverride into an
// existing role config JSON blob (e.g. ContainerWorkerConfig) and returns the
// result as a JSON string.
//
// Rules (mirror BuildConfigContent semantics):
//   - modelOverride non-empty → set top-level "model" and every agent's "model".
//   - variantOverride non-empty → set every agent's "variant".
//   - profileName non-empty and modelOverride non-empty → only override
//     primary-role agents' "model" (same as BuildConfigContent when both flags
//     are set). pf must be non-nil in this case to resolve the primary-role list.
//   - Both overrides empty → return blob unchanged (no re-marshal).
//
// The function preserves all other fields in the blob (agent identity, system
// prompt, tool allow-list, $schema, etc.).
//
// Returns an error if blob is non-empty but not valid JSON.
func ApplyModelOverrides(blob, profileName, modelOverride, variantOverride string, pf *ProfilesFile) (string, error) {
	if modelOverride == "" && variantOverride == "" {
		// Nothing to override — return blob as-is.
		return blob, nil
	}
	if blob == "" {
		// No base blob — nothing to patch.
		return blob, nil
	}

	// Parse the existing blob into a generic map.
	var cfg map[string]any
	if err := json.Unmarshal([]byte(blob), &cfg); err != nil {
		return "", fmt.Errorf("profiles: ApplyModelOverrides: parse blob: %w", err)
	}

	// Ensure the "agent" sub-map exists (it may be absent in minimal blobs).
	agentObj, _ := cfg["agent"].(map[string]any)
	if agentObj == nil {
		agentObj = make(map[string]any)
	}

	// Determine which agent names should receive the model override.
	// When profileName is set, only primary-role agents are overridden (matching
	// BuildConfigContent behaviour). Otherwise all known agents are overridden.
	var primaryAgents map[string]struct{}
	if profileName != "" && modelOverride != "" && pf != nil {
		primaryAgents = make(map[string]struct{})
		for _, name := range pf.RoleMapping["primary"] {
			primaryAgents[name] = struct{}{}
		}
	}

	// Apply modelOverride to the top-level field.
	if modelOverride != "" {
		cfg["model"] = modelOverride
	}

	// Apply overrides to each existing agent entry, and to every known agent
	// for variant (which must reach even agents not yet listed in the blob).
	//
	// Strategy:
	//  1. Update existing agent entries in agentObj.
	//  2. For variantOverride, also ensure every known agent has an entry.
	//  3. For modelOverride (no-profile path), also ensure every known agent
	//     has an entry so they don't silently use the system-default model
	//     when opened in a new blob that lacks them.

	// Collect all agent names we must touch.
	agentsToTouch := make(map[string]struct{})
	// Always touch agents already declared in the blob.
	for name := range agentObj {
		agentsToTouch[name] = struct{}{}
	}
	// When variantOverride is set, ensure every known agent is present.
	if variantOverride != "" {
		for _, name := range allKnownAgents(pf) {
			agentsToTouch[name] = struct{}{}
		}
	}
	// When modelOverride is set without a profile (→ override all agents),
	// ensure every known agent is present.
	if modelOverride != "" && profileName == "" {
		for _, name := range allKnownAgents(pf) {
			agentsToTouch[name] = struct{}{}
		}
	}

	for name := range agentsToTouch {
		entry, _ := agentObj[name].(map[string]any)
		if entry == nil {
			entry = make(map[string]any)
		}
		if modelOverride != "" {
			// Apply model override: to all agents when no profile, or only to
			// primary-role agents when a profile is set.
			if primaryAgents == nil {
				entry["model"] = modelOverride
			} else if _, isPrimary := primaryAgents[name]; isPrimary {
				entry["model"] = modelOverride
			}
		}
		if variantOverride != "" {
			entry["variant"] = variantOverride
		}
		// Only write back if the entry has content.
		if len(entry) > 0 {
			agentObj[name] = entry
		}
	}

	if len(agentObj) > 0 {
		cfg["agent"] = agentObj
	}

	out, err := json.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("profiles: ApplyModelOverrides: marshal: %w", err)
	}
	return string(out), nil
}

// ApplyProfileToBlob overlays the named profile's role-keyed model and
// variant values onto an existing role config blob (e.g.
// ContainerWorkerConfig, ContainerCoordinatorConfig, ContainerReview*Config).
//
// Background (#1207): the container_*_config blobs are pre-rendered by Nix
// from `pf.Default` and embed model identifiers in:
//
//   - The top-level "model" field (used as the session-default model).
//   - Each agent's "agent.<name>.model" field.
//   - Each agent's "agent.<name>.variant" field.
//
// When the runtime active profile differs from `pf.Default`, those baked
// values are stale: a `prism profile use gemini-hybrid && prism spawn` in
// any sandboxed isolation mode would otherwise launch with the
// `pf.Default` profile's models. ApplyProfileToBlob re-targets the model
// and variant fields to match the active profile while preserving every
// other field — agent identity, system prompt, plugin list, tool
// allow-list, permissions, $schema, etc.
//
// Rules:
//   - profileName == "" or pf == nil → return blob unchanged.
//   - profileName == pf.Default → return blob unchanged (the blob already
//     reflects the default; re-marshalling is wasted work).
//   - blob == "" → return blob unchanged (nothing to patch).
//   - profileName not present in pf.Profiles → error (caller must validate
//     before calling, but we double-check rather than silently passing
//     through a stale blob).
//   - For each role/slot pair in the named profile:
//       agent.<role>.model   ← slot.Model
//       agent.<role>.variant ← thinking value (mapped via variantFromThinking),
//                              or removed entirely when the slot's thinking
//                              is empty (so the agent inherits the session
//                              default).
//   - Top-level "model" ← coordinator slot's model, falling back to the
//     first primary-tier role (mirrors BuildConfigContent's rule).
//
// The function preserves the JSON shape of every untouched field. It does
// NOT add agent entries that the blob did not already declare, except for
// roles that exist in the active profile — that is exactly the behaviour
// needed to swap models without leaking subagents into a worker blob, etc.
//
// Returns ("", err) if blob is non-empty but not valid JSON.
func ApplyProfileToBlob(blob, profileName string, pf *ProfilesFile) (string, error) {
	if blob == "" || profileName == "" || pf == nil {
		return blob, nil
	}
	if profileName == pf.Default {
		// Blob already reflects the default profile — no-op.
		return blob, nil
	}
	entry, ok := pf.Profiles[profileName]
	if !ok {
		return "", fmt.Errorf("profiles: ApplyProfileToBlob: unknown profile %q — available: %s",
			profileName, strings.Join(AvailableProfileNames(pf), ", "))
	}

	var cfg map[string]any
	if err := json.Unmarshal([]byte(blob), &cfg); err != nil {
		return "", fmt.Errorf("profiles: ApplyProfileToBlob: parse blob: %w", err)
	}

	// Top-level "model": coordinator slot first, then first primary-tier
	// role with a slot in this profile.
	if slot, ok := entry["coordinator"]; ok && slot.Model != "" {
		cfg["model"] = slot.Model
	} else {
		for _, name := range pf.RoleMapping["primary"] {
			if slot, ok := entry[name]; ok && slot.Model != "" {
				cfg["model"] = slot.Model
				break
			}
		}
	}

	// Per-agent overlay. Only touch agent entries already declared in the
	// blob (so a worker-only blob does not gain subagent entries it never
	// had) PLUS any role with a slot in the named profile (so subagents
	// like plan/explore/review-* receive their per-profile models when the
	// blob already lists them).
	agentObj, _ := cfg["agent"].(map[string]any)
	if agentObj == nil {
		agentObj = make(map[string]any)
	}
	for role := range entry {
		// Only overlay roles that the blob already declares — staying
		// conservative about expanding a blob's agent surface, which would
		// otherwise silently widen worker blobs to include subagents.
		raw, declared := agentObj[role]
		if !declared {
			continue
		}
		agentEntry, _ := raw.(map[string]any)
		if agentEntry == nil {
			agentEntry = make(map[string]any)
		}
		slot := entry[role]
		if slot.Model != "" {
			agentEntry["model"] = slot.Model
		}
		variant := variantFromThinking(slot.Thinking)
		if variant != "" {
			agentEntry["variant"] = variant
		} else {
			// Empty thinking ⇒ remove any baked variant so the agent uses
			// opencode's default variant resolution (matches the omit-when-
			// empty rule in marshalConfigContent).
			delete(agentEntry, "variant")
		}
		agentObj[role] = agentEntry
	}
	if len(agentObj) > 0 {
		cfg["agent"] = agentObj
	}

	out, err := json.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("profiles: ApplyProfileToBlob: marshal: %w", err)
	}
	return string(out), nil
}

// marshalConfigContent builds the JSON blob for OPENCODE_CONFIG_CONTENT.
func marshalConfigContent(topModel string, agentMap map[string]agentCfg) (string, error) {
	// Build the top-level map.
	cfg := make(map[string]any)
	if topModel != "" {
		cfg["model"] = topModel
	}

	if len(agentMap) > 0 {
		agentObj := make(map[string]any)
		for name, ac := range agentMap {
			if ac.model == "" && ac.variant == "" {
				continue
			}
			entry := make(map[string]any)
			if ac.model != "" {
				entry["model"] = ac.model
			}
			// Only include variant when explicitly set — omitting it preserves
			// opencode's default variant resolution.
			if ac.variant != "" {
				entry["variant"] = ac.variant
			}
			agentObj[name] = entry
		}
		if len(agentObj) > 0 {
			cfg["agent"] = agentObj
		}
	}

	if len(cfg) == 0 {
		return "", nil
	}

	out, err := json.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("profiles: marshal config content: %w", err)
	}
	return string(out), nil
}
