// Package config — profiles.go
//
// Loads model profiles from ~/.config/prism/profiles.json and generates
// the OPENCODE_CONFIG_CONTENT JSON blob that overrides opencode's runtime
// model and variant configuration at precedence level 6 (highest).
//
// The profiles.json file is generated by Nix and has this shape:
//
//	{
//	  "default": "anthropic",
//	  "role_mapping": {
//	    "primary": ["coordinator", "plan"],
//	    "secondary": ["worker", "review", "ac"],
//	    "lightweight": ["explore", "title", "summary", "compaction"]
//	  },
//	  "profiles": {
//	    "anthropic": {
//	      "primary":     {"model": "anthropic/claude-opus-4-6"},
//	      "secondary":   {"model": "anthropic/claude-sonnet-4-6"},
//	      "lightweight": {"model": "anthropic/claude-haiku-4-5"}
//	    },
//	    "gemini-hybrid": {
//	      "primary":     {"model": "anthropic/claude-opus-4-6"},
//	      "secondary":   {"model": "google/gemini-3.1-pro-preview-customtools", "variant": "medium"},
//	      "lightweight": {"model": "anthropic/claude-haiku-4-5"}
//	    }
//	  }
//	}
//
// OPENCODE_CONFIG_CONTENT semantics:
//   - The top-level "model" is always set to the primary role's model.
//   - Each agent in role_mapping gets its own "agent.<name>.model" entry.
//   - "agent.<name>.variant" is included ONLY when the role specifies a variant.
//     Writing variant: null or variant: "" can interfere with opencode's default
//     variant resolution, so absent variants must be omitted entirely.

package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RoleConfig specifies the model (and optional variant) for an agent role.
type RoleConfig struct {
	Model   string `json:"model"`
	Variant string `json:"variant,omitempty"`
}

// ProfileEntry maps role names ("primary", "secondary", "lightweight") to
// their model+variant configs.
type ProfileEntry map[string]RoleConfig

// ProfilesFile is the on-disk structure of profiles.json.
type ProfilesFile struct {
	Default     string                  `json:"default"`
	RoleMapping map[string][]string     `json:"role_mapping"`
	Profiles    map[string]ProfileEntry `json:"profiles"`
	// ContainerWorkerConfig is the full opencode.json blob (serialised JSON
	// string) to inject as OPENCODE_CONFIG_CONTENT for worker containers.
	// Written by Nix under container_worker_config.
	ContainerWorkerConfig string `json:"container_worker_config"`
	// ContainerCoordinatorConfig is the full opencode.json blob (serialised
	// JSON string) to inject as OPENCODE_CONFIG_CONTENT for coordinator
	// containers. Written by Nix under container_coordinator_config.
	ContainerCoordinatorConfig string `json:"container_coordinator_config"`
	// AgentEnvVars holds environment variables to inject into host-mode
	// opencode processes. Values are fully expanded absolute paths (no $HOME).
	// Written by Nix under agent_env_vars. These are prepended to the
	// opencode command string in buildDirectOpencodeCmd so that sh -c
	// sessions (which do not load .zshrc or zsh aliases) receive them.
	AgentEnvVars map[string]string `json:"agent_env_vars,omitempty"`
}

// ContainerConfigForRole returns the OPENCODE_CONFIG_CONTENT blob for the
// given agent role ("worker" or "coordinator"). Returns ("", nil) when pf is
// nil (no profiles file loaded) or when the role is not a recognised container
// role (only "worker" and "coordinator" have dedicated container configs;
// subagent names like "plan", "review", etc. are valid opencode agents but do
// not have their own container configs — they inherit from the session default).
func ContainerConfigForRole(pf *ProfilesFile, role string) (string, error) {
	if pf == nil {
		return "", nil
	}
	switch role {
	case "worker":
		return pf.ContainerWorkerConfig, nil
	case "coordinator":
		return pf.ContainerCoordinatorConfig, nil
	default:
		// Not a container-level role (e.g. "plan", "review", "explore").
		// Return empty string — no config injection — without error.
		return "", nil
	}
}

// profilesFilePath returns the path to profiles.json.
// Returns "" if no home directory is discoverable.
func profilesFilePath() string {
	configHome := os.Getenv("XDG_CONFIG_HOME")
	if configHome == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return ""
		}
		configHome = filepath.Join(home, ".config")
	}
	return filepath.Join(configHome, "prism", "profiles.json")
}

// LoadProfiles reads and parses the profiles.json file.
// Returns a descriptive error if the file is missing, unreadable, or malformed.
func LoadProfiles() (*ProfilesFile, error) {
	path := profilesFilePath()
	if path == "" {
		return nil, fmt.Errorf("profiles: cannot determine profiles.json path (no home directory)")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("profiles: %s not found — run the system rebuild to generate it", path)
		}
		return nil, fmt.Errorf("profiles: read %s: %w", path, err)
	}
	var pf ProfilesFile
	if err := json.Unmarshal(data, &pf); err != nil {
		return nil, fmt.Errorf("profiles: parse %s: %w", path, err)
	}
	return &pf, nil
}

// AvailableProfileNames returns a sorted list of profile names defined in pf.
func AvailableProfileNames(pf *ProfilesFile) []string {
	names := make([]string, 0, len(pf.Profiles))
	for name := range pf.Profiles {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// agentCfg holds the model and variant for a single opencode agent.
type agentCfg struct {
	model   string
	variant string
}

// BuildConfigContent generates the OPENCODE_CONFIG_CONTENT JSON string for the
// given spawn options.
//
// Rules:
//   - If profileName is non-empty, load that profile and apply it.
//   - If modelOverride is non-empty (without a profile), set top-level model
//     and all agent models to modelOverride.
//   - If modelOverride is set alongside profileName, it overrides top-level
//     model AND the primary-role agents only; secondary/lightweight agents
//     retain profile values.
//   - If variantOverride is non-empty, set "variant" on ALL agent configs.
//   - Returns ("", nil) when no flags are set (no injection needed).
//
// pf may be nil when no profile flag is used; it is only consulted when
// profileName is non-empty.
func BuildConfigContent(pf *ProfilesFile, profileName, modelOverride, variantOverride string) (string, error) {
	if profileName == "" && modelOverride == "" && variantOverride == "" {
		return "", nil
	}

	// agentMap accumulates per-agent configs keyed by agent name.
	agentMap := make(map[string]agentCfg)
	topModel := ""

	if profileName != "" {
		if pf == nil {
			return "", fmt.Errorf("profiles: profile %q requested but profiles file not loaded", profileName)
		}
		entry, ok := pf.Profiles[profileName]
		if !ok {
			available := AvailableProfileNames(pf)
			return "", fmt.Errorf("profiles: unknown profile %q — available: %s",
				profileName, strings.Join(available, ", "))
		}

		// Set top-level model from primary role.
		if rc, ok := entry["primary"]; ok {
			topModel = rc.Model
		}

		// Expand role mapping to per-agent configs.
		for role, agents := range pf.RoleMapping {
			rc, ok := entry[role]
			if !ok {
				continue
			}
			for _, agentName := range agents {
				agentMap[agentName] = agentCfg{
					model:   rc.Model,
					variant: rc.Variant,
				}
			}
		}
	}

	// Apply modelOverride.
	if modelOverride != "" {
		topModel = modelOverride
		if profileName != "" {
			// Only override primary-role agents.
			if pf != nil {
				for _, agentName := range pf.RoleMapping["primary"] {
					ac := agentMap[agentName]
					ac.model = modelOverride
					agentMap[agentName] = ac
				}
			}
		} else {
			// No profile: override all agents.
			// We need the full agent list. Use a known hardcoded default set
			// since we may not have a profiles file.
			allAgents := allKnownAgents(pf)
			for _, agentName := range allAgents {
				ac := agentMap[agentName]
				ac.model = modelOverride
				agentMap[agentName] = ac
			}
		}
	}

	// Apply variantOverride.
	if variantOverride != "" {
		// Collect all agents we know about.
		allAgents := allKnownAgents(pf)
		for _, agentName := range allAgents {
			ac := agentMap[agentName]
			ac.variant = variantOverride
			agentMap[agentName] = ac
		}
	}

	// If neither profile nor model was set we still have topModel = "".
	// Don't emit top-level "model" key when it's empty.
	// Build the JSON structure.
	return marshalConfigContent(topModel, agentMap)
}

// allKnownAgents returns all agent names known from the profiles file's role
// mapping, or a hardcoded fallback set when pf is nil.
func allKnownAgents(pf *ProfilesFile) []string {
	if pf != nil {
		seen := make(map[string]struct{})
		var agents []string
		for _, roleAgents := range pf.RoleMapping {
			for _, a := range roleAgents {
				if _, ok := seen[a]; !ok {
					seen[a] = struct{}{}
					agents = append(agents, a)
				}
			}
		}
		sort.Strings(agents)
		return agents
	}
	// Hardcoded fallback: the standard set of opencode agents prism uses.
	return []string{
		"ac",
		"compaction",
		"coordinator",
		"explore",
		"plan",
		"review",
		"summary",
		"title",
		"worker",
	}
}

// marshalConfigContent builds the JSON blob for OPENCODE_CONFIG_CONTENT.
func marshalConfigContent(topModel string, agentMap map[string]agentCfg) (string, error) {
	// Build the top-level map.
	cfg := make(map[string]any)
	if topModel != "" {
		cfg["model"] = topModel
	}

	if len(agentMap) > 0 {
		agentObj := make(map[string]any)
		for name, ac := range agentMap {
			if ac.model == "" && ac.variant == "" {
				continue
			}
			entry := make(map[string]any)
			if ac.model != "" {
				entry["model"] = ac.model
			}
			// Only include variant when explicitly set — omitting it preserves
			// opencode's default variant resolution.
			if ac.variant != "" {
				entry["variant"] = ac.variant
			}
			agentObj[name] = entry
		}
		if len(agentObj) > 0 {
			cfg["agent"] = agentObj
		}
	}

	if len(cfg) == 0 {
		return "", nil
	}

	out, err := json.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("profiles: marshal config content: %w", err)
	}
	return string(out), nil
}
