// Package config — profiles.go
//
// Loads model profiles from ~/.config/prism/profiles.json and generates
// per-role slot configuration for pi sessions.
//
// As of #1612 the profile schema is flat per-role: each profile is a map from
// session role (coordinator, worker, ac, retro, investigate, review-goal,
// review-code, review-security, review-qa, review-context) to a per-role
// configuration record carrying provider, model, thinking, and
// systemPromptPath. The legacy tier-bucket model (roleMapping, primary /
// secondary / lightweight) and all pi harness-switching machinery
// are removed.
//
// The profiles.json file is generated by Nix and has this shape:
//
//	{
//	  "default": "anthropic",
//	  "profiles": {
//	    "anthropic": {
//	      "coordinator": {"provider":"anthropic","model":"anthropic/claude-opus-4-7","thinking":"medium","systemPromptPath":"/home/user/.config/prism/agents/coordinator.md"},
//	      "worker":      {"provider":"anthropic","model":"anthropic/claude-sonnet-4-6","thinking":"low","systemPromptPath":"/home/user/.config/prism/agents/worker.md"},
//	      ...
//	    },
//	    "anthropic-opus": {...},
//	    "gemini-hybrid":  {...}
//	  }
//	}

package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RoleSlot is the per-role configuration record.
//
// Field semantics:
//   - Provider: routing provider name.
//   - Model: model identifier for this role's session.
//   - Thinking: reasoning level. Passed to pi verbatim on argv as
//     `--thinking <value>` (see container.PIInvocation).
//
// The role system-prompt is no longer carried in the slot: it is injected at
// runtime by the prism PI extension (before_agent_start) from
// ~/.config/prism/agents/<role>.md (design #2031).
type RoleSlot struct {
	Provider string `json:"provider,omitempty"`
	Model    string `json:"model"`
	Thinking string `json:"thinking,omitempty"`
}

// ProfileEntry maps session role names ("coordinator", "worker", "review-goal",
// ...) to their per-role slot configs.
type ProfileEntry map[string]RoleSlot

// ProfilesFile is the on-disk structure of profiles.json.
type ProfilesFile struct {
	Default  string                  `json:"default"`
	Profiles map[string]ProfileEntry `json:"profiles"`
	// AgentEnvVars holds environment variables to inject into host-mode
	// pi processes. Values are fully expanded absolute paths (no $HOME).
	// Written by Nix under agent_env_vars.
	AgentEnvVars map[string]string `json:"agent_env_vars,omitempty"`
	// ContainerResources holds per-container resource cap values that the
	// removed container isolation mode passed to the container runtime.
	// Unused by current isolation modes; retained for config-shape
	// compatibility. Written by Nix under container_resources.
	ContainerResources ContainerResources `json:"container_resources,omitempty"`
	// QuickProfiles holds lightweight model configs for prism quick subcommands.
	// Written by Nix under quick_profiles.
	QuickProfiles map[string]QuickProfile `json:"quick_profiles,omitempty"`
}

// ContainerResources holds the per-container resource cap values that the
// removed container isolation mode consumed. Unused by current isolation
// modes; retained for config-shape compatibility. Zero values / empty
// strings mean "no flag emitted".
type ContainerResources struct {
	// MemoryMax is the memory cap (e.g. "8g"). Empty string means no cap.
	MemoryMax string `json:"memoryMax,omitempty"`
	// MemorySwapMax is the memory+swap cap (e.g. "8g"). Empty string means
	// no cap.
	MemorySwapMax string `json:"memorySwapMax,omitempty"`
	// PidsLimit is the process-count cap. Zero means no cap.
	PidsLimit int `json:"pidsLimit,omitempty"`
}

// QuickProfile holds the model config for a prism quick subcommand (e.g. "pr").
//
// As of #2118, prism quick pr invokes `pi --print` instead of OpenRouter
// over HTTP; Model is now a pi model specifier (e.g.
// "anthropic/claude-sonnet-4-6") and the legacy ProviderOrder field is
// dropped. Unknown fields in profiles.json are ignored by Go's JSON
// decoder, so loading a profiles.json that still carries a `providerOrder`
// key (e.g. an older system rebuild) is silently tolerated.
type QuickProfile struct {
	// Model is the pi model specifier passed to `pi --model`.
	Model string `json:"model"`
}

// profilesFilePath returns the path to profiles.json.
// Returns "" if no home directory is discoverable.
func profilesFilePath() string {
	configHome := os.Getenv("XDG_CONFIG_HOME")
	if configHome == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return ""
		}
		configHome = filepath.Join(home, ".config")
	}
	return filepath.Join(configHome, "prism", "profiles.json")
}

// HarnessValidator is kept for compatibility with callers that set it during
// init(). It is no longer used by LoadProfiles (the harness.default field and
// DefaultHarness validation were removed in #1612). Setting it is a no-op.
var HarnessValidator func(name string) (validNames []string, ok bool)

// LoadProfiles reads and parses the profiles.json file.
// Returns a descriptive error if the file is missing, unreadable, or malformed.
// Unknown JSON fields are ignored so old profiles.json files with stale keys
// (role_mapping, default_harness, container_*_config) load cleanly.
func LoadProfiles() (*ProfilesFile, error) {
	path := profilesFilePath()
	if path == "" {
		return nil, fmt.Errorf("profiles: cannot determine profiles.json path (no home directory)")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("profiles: %s not found — run the system rebuild to generate it", path)
		}
		return nil, fmt.Errorf("profiles: read %s: %w", path, err)
	}
	var pf ProfilesFile
	if err := json.Unmarshal(data, &pf); err != nil {
		return nil, fmt.Errorf("profiles: parse %s: %w", path, err)
	}
	return &pf, nil
}

// AvailableProfileNames returns a sorted list of profile names defined in pf.
func AvailableProfileNames(pf *ProfilesFile) []string {
	names := make([]string, 0, len(pf.Profiles))
	for name := range pf.Profiles {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// SlotForRole returns the slot configured for the given role in the named
// profile.
//
// Returns (RoleSlot{}, false) when pf is nil, the profile is unknown, or the
// profile defines no slot for that role.
func SlotForRole(pf *ProfilesFile, profileName, role string) (RoleSlot, bool) {
	if pf == nil {
		return RoleSlot{}, false
	}
	entry, ok := pf.Profiles[profileName]
	if !ok {
		return RoleSlot{}, false
	}
	slot, ok := entry[role]
	return slot, ok
}

// RequireSlot validates that the named profile defines a slot for the given
// session role. It returns nil when the slot is present, or a descriptive
// error listing every role the active profile currently defines.
//
// This is the spawn-time edge-case gate from #1206: a session whose role
// cannot be resolved against the active profile must fail early with a clear
// diagnostic.
func RequireSlot(pf *ProfilesFile, profileName, role string) error {
	if pf == nil {
		return fmt.Errorf("profiles: profile %q requires slot %q but profiles file not loaded", profileName, role)
	}
	entry, ok := pf.Profiles[profileName]
	if !ok {
		return fmt.Errorf("profiles: unknown profile %q — available: %s",
			profileName, strings.Join(AvailableProfileNames(pf), ", "))
	}
	if _, ok := entry[role]; ok {
		return nil
	}
	defined := make([]string, 0, len(entry))
	for name := range entry {
		defined = append(defined, name)
	}
	sort.Strings(defined)
	return fmt.Errorf(
		"profiles: profile %q does not define a slot for session role %q — defined slots: %s",
		profileName, role, strings.Join(defined, ", "),
	)
}

// Note (#2854): prism used to render a profile slot into a JSON harness-config
// blob here (BuildConfigContent) and ship it to pi as the PI_CONFIG_CONTENT
// env var, or as a per-session temp file. pi read neither, so both transports
// were retired. The single live carrier of provider / model / thinking is the
// argv channel from #2086: buildDirectAgentCmd (host) and
// appendAgentRunOverrides + populatePIConfig + PIInvocation (bwrap,
// sandbox-exec).
