//go:build darwin

package integration_test

// sandbox_exec_profile_darwin_test.go — integration tests for the SBPL profile
// generated by Manager.PrepareSandboxExec() (issue #1187).
//
// These tests close the gap that allowed issue #1187 to ship: the existing unit
// tests in internal/container/sandbox_exec_test.go assert profile string
// content (substring checks) but never invoke the real /usr/bin/sandbox-exec
// binary against a generated profile. This file provides that end-to-end
// coverage.
//
// Test structure:
//
//  1. TestSandboxExecProfile_EtcReadable — positive test.
//     Generates a profile via Manager.PrepareSandboxExec(), augments it with
//     the minimum extras needed for a Nix-built test binary to start under the
//     sandbox (see "Test harness extras" note below), and invokes sandbox-exec
//     to stat /etc/hosts. Asserts exit 0.
//
//  2. TestSandboxExecProfile_MissingEtcDenied — negative / regression test.
//     Takes the same augmented profile but removes the (subpath "/etc") rule
//     that was added by the #1187 fix. Asserts that the stat fails (non-zero
//     exit). This proves the test catches the original regression.
//
// # Test binary
//
// We use the Nix-built bash (resolved via exec.LookPath + filepath.EvalSymlinks
// to its /nix/store/... path) as the test binary. Nix-built binaries are
// ad-hoc-signed (not Apple-Software-Signing), so they do not trigger the
// dyld CacheFinder SIGABRT that Apple-signed system binaries emit under a
// deny-default SBPL profile (that is a separate, out-of-scope issue tracked
// in #1190).
//
// # Test harness extras
//
// The generated profile uses specific subpath rules (e.g. (subpath "/nix")),
// not the catch-all (subpath "/"). Nix-built binaries need to read the root
// directory inode "/" itself during dyld startup — not just subtrees under it.
// Without (literal "/") the binary SIGABRTs before running any user code.
//
// The integration test appends three lines to the generated profile content
// before writing the test profile:
//
//   (allow file-read* (literal "/") (subpath "/dev"))
//   (allow file-read* file-write* (subpath "/private/tmp"))
//
// These are testing infrastructure only — they are NOT added to the production
// profile. They let the test binary start; they do not affect whether /etc is
// or is not accessible (which is what we are actually testing).
//
// Note: PrepareSandboxExec() creates its own sandboxExecIsolator internally
// (it does not use m.isolator), so calling container.New(cfg) is sufficient —
// no isolator swapping is needed for these tests.

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/prismatic-koi/prism/internal/container"
)

const sandboxExecPath = "/usr/bin/sandbox-exec"

// requireSandboxExec skips the test when /usr/bin/sandbox-exec is not present
// or when the test is running inside the Nix build sandbox (where sandbox-exec
// is itself restricted and cannot apply SBPL profiles).
func requireSandboxExec(t *testing.T) {
	t.Helper()

	// The Nix build sandbox sets NIX_BUILD_TOP to a path under /nix/var/nix/builds/
	// and sets HOME to /homeless-shelter. Running sandbox-exec inside the Nix
	// sandbox produces "sandbox_apply: Operation not permitted" because the Nix
	// sandboxed builder cannot nest a second sandbox-exec invocation.
	if nixBuildTop := os.Getenv("NIX_BUILD_TOP"); nixBuildTop != "" {
		t.Skipf("skipping sandbox-exec integration test inside Nix build sandbox (NIX_BUILD_TOP=%s)", nixBuildTop)
	}

	if _, err := os.Stat(sandboxExecPath); err != nil {
		t.Skipf("sandbox-exec not found at %s: %v", sandboxExecPath, err)
	}
}

// requireNixBash resolves the Nix-built bash binary via PATH → symlink chain
// and returns its /nix/store/... absolute path. Skips the test when bash is
// not found or does not resolve to a Nix store path.
//
// We use a Nix-built binary rather than an Apple-signed system binary (/bin/bash)
// because Apple-signed binaries SIGABRT in dyld4::CacheFinder under a
// deny-default SBPL profile — a separate issue tracked in #1190.
func requireNixBash(t *testing.T) string {
	t.Helper()

	bashPath, err := exec.LookPath("bash")
	if err != nil {
		t.Skipf("bash not found in PATH: %v", err)
	}

	resolved, err := filepath.EvalSymlinks(bashPath)
	if err != nil {
		t.Skipf("EvalSymlinks(%q): %v", bashPath, err)
	}

	if !strings.HasPrefix(resolved, "/nix/store/") {
		t.Skipf("bash resolves to %q which is not a /nix/store/ path — cannot use as test binary (Apple-signed binaries SIGABRT under deny-default sandbox, see #1190)", resolved)
	}

	return resolved
}

// newProfileManager creates a Manager with a minimal Config suitable for
// generating a sandbox-exec profile in integration tests. The Worktree points
// to a fresh temp dir so the profile includes a real subpath rule.
//
// Note: container.New() initialises the Manager with a podmanIsolator by
// default, but Manager.PrepareSandboxExec() creates its own sandboxExecIsolator
// internally, so no isolator override is needed.
func newProfileManager(t *testing.T) *container.Manager {
	t.Helper()
	// Sanitise the test name for use as an InstanceID: remove characters that
	// are invalid in filesystem paths (e.g. "/" from subtest names).
	instanceID := "integ-sbx-" + strings.ReplaceAll(t.Name(), "/", "-")
	cfg := container.Config{
		SessionName: "integ-sandbox-exec-profile-test",
		InstanceID:  instanceID,
		Worktree:    t.TempDir(),
	}
	return container.New(cfg)
}

// augmentProfileForTest takes the SBPL profile content generated by
// Manager.PrepareSandboxExec() and appends the minimum extras needed for a
// Nix-built binary to start under the sandbox during testing:
//
//   - (literal "/") — lets dyld read the root directory inode during startup.
//     Without this, any binary SIGABRTs before executing user code when the
//     profile uses specific subpath rules rather than (subpath "/").
//   - (subpath "/dev") — /dev/null and /dev/tty are accessed by bash shell-init.
//   - (subpath "/private/tmp") with file-write* — bash needs a writable temp dir.
//
// These additions are testing infrastructure only; they are NOT added to the
// production profile. They do not affect whether /etc is accessible — that is
// determined solely by the (subpath "/etc") rule (or its absence) in the
// generated profile.
func augmentProfileForTest(profile string) string {
	extras := "\n" +
		";; --- test-harness extras (not in production profile) ---\n" +
		"(allow file-read* (literal \"/\") (subpath \"/dev\"))\n" +
		"(allow file-read* file-write* (subpath \"/private/tmp\"))\n"
	return profile + extras
}

// TestSandboxExecProfile_EtcReadable is the primary integration smoke test for
// issue #1187. It generates a profile via Manager.PrepareSandboxExec(), augments
// it with test-harness extras (see augmentProfileForTest), and invokes
// sandbox-exec to stat /etc/hosts. Asserts exit 0.
//
// Before the fix (missing (subpath "/etc")), the stat call would fail with
// "Operation not permitted" (non-zero exit) because the kernel denies access
// to any path under /etc that is not also accessible via /private/etc.
func TestSandboxExecProfile_EtcReadable(t *testing.T) {
	if runtime.GOOS != "darwin" {
		t.Skip("sandbox-exec is Darwin-only")
	}
	requireSandboxExec(t)
	nixBash := requireNixBash(t)

	m := newProfileManager(t)

	args, err := m.PrepareSandboxExec()
	t.Cleanup(func() {
		if stagingHome, homeErr := m.SandboxExecHomePath(); homeErr == nil {
			_ = os.RemoveAll(stagingHome)
		}
		if len(args) >= 3 {
			_ = os.Remove(args[2])
		}
	})
	if err != nil {
		t.Fatalf("PrepareSandboxExec: %v", err)
	}

	// args shape: ["sandbox-exec", "-f", "<profile_path>", ...]
	if len(args) < 3 || args[0] != "sandbox-exec" || args[1] != "-f" {
		t.Fatalf("PrepareSandboxExec returned unexpected args shape: %v", args)
	}
	generatedProfilePath := args[2]

	origContent, err := os.ReadFile(generatedProfilePath)
	if err != nil {
		t.Fatalf("read generated profile: %v", err)
	}

	// Verify the /etc rule is present before testing (if it's missing the fix
	// wasn't applied and the positive test would be testing the wrong thing).
	const etcRule = `(subpath "/etc")`
	if !strings.Contains(string(origContent), etcRule) {
		t.Fatalf("generated profile is missing %q — the fix for issue #1187 has not been applied.\nProfile:\n%s",
			etcRule, string(origContent))
	}

	// Write the augmented test profile.
	augmented := augmentProfileForTest(string(origContent))
	testProfilePath := generatedProfilePath + ".integ-test"
	if err := os.WriteFile(testProfilePath, []byte(augmented), 0o600); err != nil {
		t.Fatalf("write test profile: %v", err)
	}
	t.Cleanup(func() { _ = os.Remove(testProfilePath) })

	// Run: sandbox-exec -f <augmented_profile> <nix_bash> -c 'stat /etc/hosts'
	// /etc/hosts is always present on macOS and lives under the /etc symlink
	// (→ /private/etc/hosts). If /etc is not in the allow list, stat returns
	// "Operation not permitted" and the command exits non-zero.
	cmd := exec.Command(sandboxExecPath, "-f", testProfilePath,
		nixBash, "-c", "stat /etc/hosts")
	out, runErr := cmd.CombinedOutput()
	if runErr != nil {
		t.Errorf("sandbox-exec stat /etc/hosts failed with profile containing %q.\n"+
			"This means /etc is not accessible inside the sandbox — the fix for #1187 is missing or the profile is wrong.\n"+
			"Exit: %v\nOutput: %s\nTest profile: %s",
			etcRule, runErr, string(out), testProfilePath)
	}
}

// TestSandboxExecProfile_MissingEtcDenied is the negative regression test for
// issue #1187. It takes the generated profile, removes the (subpath "/etc")
// rule, and asserts that stat /etc/hosts fails (non-zero exit).
//
// This test proves that TestSandboxExecProfile_EtcReadable above is not
// trivially passing for unrelated reasons: removing the /etc allow rule causes
// a measurable, observable denial.
func TestSandboxExecProfile_MissingEtcDenied(t *testing.T) {
	if runtime.GOOS != "darwin" {
		t.Skip("sandbox-exec is Darwin-only")
	}
	requireSandboxExec(t)
	nixBash := requireNixBash(t)

	m := newProfileManager(t)

	args, err := m.PrepareSandboxExec()
	t.Cleanup(func() {
		if stagingHome, homeErr := m.SandboxExecHomePath(); homeErr == nil {
			_ = os.RemoveAll(stagingHome)
		}
		if len(args) >= 3 {
			_ = os.Remove(args[2])
		}
	})
	if err != nil {
		t.Fatalf("PrepareSandboxExec: %v", err)
	}
	if len(args) < 3 {
		t.Fatalf("unexpected args: %v", args)
	}
	origContent, readErr := os.ReadFile(args[2])
	if readErr != nil {
		t.Fatalf("read generated profile: %v", readErr)
	}

	const etcRule = "  (subpath \"/etc\")\n"
	if !strings.Contains(string(origContent), etcRule) {
		// The fix isn't applied — this test can't demonstrate the regression.
		t.Fatalf("generated profile is missing the (subpath \"/etc\") rule.\n"+
			"The fix for issue #1187 has not been applied; cannot demonstrate regression.\nProfile:\n%s",
			string(origContent))
	}

	// Remove the (subpath "/etc") rule to simulate the pre-fix profile.
	mutated := strings.ReplaceAll(string(origContent), etcRule, "")

	// Augment with test-harness extras (same as positive test, so the binary
	// can start — the /etc removal is what we're actually testing).
	augmentedMutated := augmentProfileForTest(mutated)

	mutatedPath := args[2] + ".integ-regression"
	if writeErr := os.WriteFile(mutatedPath, []byte(augmentedMutated), 0o600); writeErr != nil {
		t.Fatalf("write mutated profile: %v", writeErr)
	}
	t.Cleanup(func() { _ = os.Remove(mutatedPath) })

	// Run: sandbox-exec -f <mutated_profile> <nix_bash> -c 'stat /etc/hosts'
	// Without (subpath "/etc"), the kernel denies access to /etc/hosts and
	// stat returns "Operation not permitted". The command must exit non-zero.
	cmd := exec.Command(sandboxExecPath, "-f", mutatedPath,
		nixBash, "-c", "stat /etc/hosts")
	out, runErr := cmd.CombinedOutput()
	if runErr == nil {
		t.Errorf("sandbox-exec stat /etc/hosts succeeded (exit 0) even WITHOUT the /etc allow rule.\n"+
			"The regression test is not catching the denial — investigate why /etc is accessible without the rule.\n"+
			"Output: %s\nMutated profile: %s", string(out), mutatedPath)
	} else {
		t.Logf("ka pai — /etc correctly denied without (subpath \"/etc\") allow rule (exit: %v)", runErr)
	}
}
