//go:build darwin

package integration_test

// sandbox_exec_profile_darwin_test.go — system-paths integration tests for
// the SBPL profile generated by Manager.PrepareSandboxExec() (issue #1187 +
// #1192).
//
// These tests close the gap that allowed issue #1187 to ship: the unit tests
// in internal/container/sandbox_exec_test.go assert profile string content
// (substring checks) but never invoke the real /usr/bin/sandbox-exec binary
// against a generated profile. This file provides the end-to-end coverage for
// the read-only system-paths allow set:
//
//  - TestSandboxExecProfile_EtcReadable — positive smoke against /etc.
//  - TestSandboxExecProfile_MissingEtcDenied — the original /etc-only
//    regression test from #1187.
//  - TestSandboxExecProfile_SystemPathRemovalDenied — table-driven extension
//    that proves removing ANY single subpath from the system-paths allow
//    list breaks an operation that depends on it (issue #1192). This guards
//    against future regressions silently removing the wrong path.
//
// Shared helpers (requireSandboxExec, requireNixBash, newProfileManager,
// augmentProfileForTest, withMutatedProfile, ...) live in
// sandbox_exec_helpers_darwin_test.go.
//
// See docs/sandbox-exec-testing.md for the convention these tests support.

import (
	"os/exec"
	"runtime"
	"strings"
	"testing"
)

// TestSandboxExecProfile_EtcReadable is the primary integration smoke test
// for issue #1187. It generates a profile via Manager.PrepareSandboxExec(),
// augments it with test-harness extras (see augmentProfileForTest), and
// invokes sandbox-exec to stat /etc/hosts. Asserts exit 0.
//
// The Manager is constructed without BareRoot (newProfileManager, not
// newProfileManagerWithBareRoot) so the BareRoot ancestor block — which
// would emit a (subpath "/") metadata allow that masks the effect of
// removing other system-paths rules — does not fire. This keeps the
// negative tests in this file sensitive to per-subpath rule removal.
//
// Before the fix (missing (subpath "/etc")), the stat call would fail with
// "Operation not permitted" (non-zero exit) because the kernel denies
// access to any path under /etc that is not also accessible via /private/etc.
func TestSandboxExecProfile_EtcReadable(t *testing.T) {
	if runtime.GOOS != "darwin" {
		t.Skip("sandbox-exec is Darwin-only")
	}
	requireSandboxExec(t)
	nixBash := requireNixBash(t)

	m := newProfileManager(t)
	prepared, _ := preparePositiveProfile(t, m)

	// Verify the /etc rule is present before testing — if it's missing the
	// fix wasn't applied and the positive test would be testing the wrong
	// thing.
	const etcRule = `(subpath "/etc")`
	if !strings.Contains(prepared.content, etcRule) {
		t.Fatalf("generated profile is missing %q — the fix for issue #1187 has not been applied.\nProfile:\n%s",
			etcRule, prepared.content)
	}

	testProfilePath := writeAugmentedPositiveProfile(t, prepared)

	// Run: sandbox-exec -f <augmented_profile> <nix_bash> -c 'stat /etc/hosts'
	// /etc/hosts is always present on macOS and lives under the /etc symlink
	// (→ /private/etc/hosts). If /etc is not in the allow list, stat returns
	// "Operation not permitted" and the command exits non-zero.
	cmd := exec.Command(sandboxExecPath, "-f", testProfilePath,
		nixBash, "-c", "stat /etc/hosts")
	out, runErr := cmd.CombinedOutput()
	if runErr != nil {
		t.Errorf("sandbox-exec stat /etc/hosts failed with profile containing %q.\n"+
			"This means /etc is not accessible inside the sandbox — the fix for #1187 is missing or the profile is wrong.\n"+
			"Exit: %v\nOutput: %s\nTest profile: %s",
			etcRule, runErr, string(out), testProfilePath)
	}
}

// TestSandboxExecProfile_MissingEtcDenied is the negative regression test for
// issue #1187. It takes the generated profile, removes the (subpath "/etc")
// rule, and asserts that stat /etc/hosts fails (non-zero exit).
//
// This test proves that TestSandboxExecProfile_EtcReadable above is not
// trivially passing for unrelated reasons: removing the /etc allow rule
// causes a measurable, observable denial.
func TestSandboxExecProfile_MissingEtcDenied(t *testing.T) {
	if runtime.GOOS != "darwin" {
		t.Skip("sandbox-exec is Darwin-only")
	}
	requireSandboxExec(t)
	nixBash := requireNixBash(t)

	m := newProfileManager(t)

	const etcRule = "  (subpath \"/etc\")\n"
	mutatedPath := withMutatedProfile(t, m, func(p string) string {
		return strings.ReplaceAll(p, etcRule, "")
	})

	// Run: sandbox-exec -f <mutated_profile> <nix_bash> -c 'stat /etc/hosts'
	// Without (subpath "/etc"), the kernel denies access to /etc/hosts and
	// stat returns "Operation not permitted". The command must exit non-zero.
	cmd := exec.Command(sandboxExecPath, "-f", mutatedPath,
		nixBash, "-c", "stat /etc/hosts")
	out, runErr := cmd.CombinedOutput()
	if runErr == nil {
		t.Errorf("sandbox-exec stat /etc/hosts succeeded (exit 0) even WITHOUT the /etc allow rule.\n"+
			"The regression test is not catching the denial — investigate why /etc is accessible without the rule.\n"+
			"Output: %s\nMutated profile: %s", string(out), mutatedPath)
	} else {
		t.Logf("ka pai — /etc correctly denied without (subpath \"/etc\") allow rule (exit: %v)", runErr)
	}
}

// TestSandboxExecProfile_SystemPathRemovalDenied is the broader regression
// guard for the system-paths allow list (issue #1192). For each subpath that
// the system-paths allow rule covers AND that has an observable effect on a
// Nix-built bash invocation, this table-driven test:
//
//  1. Removes only that subpath from the profile.
//  2. Runs a probe command that depends on that subpath being readable.
//  3. Asserts the probe fails — proving the test is not a no-op.
//
// This is the AC #6 of #1192: "the negative test for the system-paths allow
// set is wired such that removing any single subpath from the file-read
// allow list fails the test — not just removing /etc". A future PR that
// silently removes the wrong system path (e.g. swaps /etc for /Etc, or drops
// /private/etc by accident) would otherwise pass the existing /etc-only
// negative test even though it has broken a different, equally critical
// allow rule.
//
// The probe set is intentionally small: it covers the system paths whose
// removal causes Nix-bash + stat to fail with EPERM at the kernel level.
// Some subpaths in the allow list (e.g. /Applications/Xcode.app, /var/select)
// have no observable effect on a basic bash + stat probe and are not
// included — adding probes for them would require running heavier binaries
// (xcrun, which-style lookups) inside the sandbox, which is fragile in a
// test environment.
//
// Deliberate subpath coverage:
//   - /nix          — bash itself lives under /nix; without it, dyld cannot
//     even load the binary. The sandbox blocks process start.
//   - /etc          — stat /etc/hosts (the original #1187 regression).
//   - /private/etc  — stat /private/etc/hosts directly via the canonical
//     path. /etc → /private/etc symlink non-transparency
//     means both forms must be allowed independently.
func TestSandboxExecProfile_SystemPathRemovalDenied(t *testing.T) {
	if runtime.GOOS != "darwin" {
		t.Skip("sandbox-exec is Darwin-only")
	}
	requireSandboxExec(t)
	nixBash := requireNixBash(t)

	cases := []struct {
		// name is the t.Run subtest name.
		name string

		// subpathRule is the EXACT line (including leading two-space indent
		// and trailing newline) that withMutatedProfile will strip from the
		// generated profile. We require an exact match so that a future
		// reformat of the profile generator (e.g. tab indents, different
		// quoting) immediately fails this test rather than silently passing
		// because the strings.ReplaceAll matched nothing.
		subpathRule string

		// probe is the bash one-liner whose exit code must change from 0
		// (with the rule present) to non-zero (with the rule removed).
		probe string
	}{
		{
			name:        "nix-store",
			subpathRule: "  (subpath \"/nix\")\n",
			// bash itself is at /nix/store/.../bin/bash. With (subpath "/nix")
			// removed, dyld cannot map the binary's pages and execve fails.
			// Any probe will do — even `:` (the no-op builtin) — because the
			// failure is at process start.
			probe: ":",
		},
		{
			name:        "etc",
			subpathRule: "  (subpath \"/etc\")\n",
			probe:       "stat /etc/hosts",
		},
		{
			name:        "private-etc",
			subpathRule: "  (subpath \"/private/etc\")\n",
			// /etc → /private/etc symlink. With (subpath "/private/etc")
			// removed, accessing the canonical /private/etc/hosts path
			// directly must fail because the kernel does not transparently
			// follow /etc → /private/etc for SBPL rule resolution.
			probe: "stat /private/etc/hosts",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			m := newProfileManager(t)

			mutatedPath := withMutatedProfile(t, m, func(p string) string {
				return strings.ReplaceAll(p, tc.subpathRule, "")
			})

			cmd := exec.Command(sandboxExecPath, "-f", mutatedPath,
				nixBash, "-c", tc.probe)
			out, runErr := cmd.CombinedOutput()
			if runErr == nil {
				t.Errorf("removing %q from the profile did NOT cause the probe %q to fail.\n"+
					"This means the negative test for this subpath is silently passing for an unrelated reason — investigate.\n"+
					"Output: %s\nMutated profile: %s",
					strings.TrimSpace(tc.subpathRule), tc.probe, string(out), mutatedPath)
			} else {
				t.Logf("ka pai — %s correctly denied without %s (exit: %v)",
					tc.probe, strings.TrimSpace(tc.subpathRule), runErr)
			}
		})
	}
}
