package container

// sandbox_exec_home.go — per-session staging HOME builder for sandbox-exec mode.
//
// PrepareSandboxExecHome populates a staging HOME directory at
// ~/.local/state/prism/sessions/<instance_id>/home/ with symlinks to the real
// credential, config, and cache paths the agent needs. The SBPL profile grants
// read access to every resolved symlink target, while the staging HOME itself
// is writable so the sandbox can do things like write to ~/.cache/opencode
// inside it (which symlinks through to the host path).
//
// Design decisions locked by the coordinator in issue #1017:
//
//  1. (retired in #2243, Step 3c of #2132) .claude/ used to be a
//     write-through symlink to host ~/.claude. claude-code now resolves its
//     config dir (and .claude.json) via the CLAUDE_CONFIG_DIR env var at the
//     host XDG path ~/.config/claude — generateProfile emits an explicit RW
//     (subpath ~/.config/claude) grant instead.
//
//  2. (retired in #2245, Step 3f of #2132) .config/prism/agents/ used to be
//     symlinked into the staging HOME for ALL roles (issue #2032; design
//     #2031). generateProfile now emits an explicit RO
//     (subpath ~/.config/prism/agents) grant on the real host path instead.
//
//  3. (retired in #2245, Step 3e of #2132) .cache/nix/ used to be an RW
//     symlink to ~/.cache/nix. generateProfile now emits an explicit RW
//     (subpath ~/.cache/nix) grant on the real host path instead (and the
//     bwrap mount in mounts.go StandardSandboxMounts is OptionalIfMissing).

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// sandboxExecHomePath returns the staging HOME path for the given instance ID.
// The path is:
//
//	~/.local/state/prism/sessions/<instance_id>/home/
//
// This is the per-session staging HOME that PrepareSandboxExecHome creates and
// populates with symlinks. InstanceID is used as the namespace key so concurrent
// sessions have independent staging dirs.
func (m *Manager) sandboxExecHomePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}
	if home == "" {
		return "", fmt.Errorf("container: sandbox-exec: cannot determine user home directory")
	}
	instanceID := m.cfg.InstanceID
	if instanceID == "" {
		// Fall back to session name when InstanceID is not set (e.g. tests
		// that construct Manager directly without a full spawn lifecycle).
		// Use the container name (slugified session name) to stay safe for
		// filesystem use.
		instanceID = m.name
	}
	return filepath.Join(home, ".local", "state", "prism", "sessions", instanceID, "home"), nil
}

// PrepareSandboxExecHome creates the per-session staging HOME directory and
// populates it with symlinks to the real credential, config, and cache paths
// that the agent needs. Returns the absolute path to the staging HOME.
//
// The staging HOME layout mirrors the bwrap sandbox home layout (every path
// that bwrap creates via bind-mount, sandbox-exec achieves via a symlink). The
// SBPL profile generated by generateProfile grants read access to every resolved
// symlink target so the sandbox can traverse the symlinks.
//
// Rules:
//   - When a source path does not exist on the host, the symlink is skipped.
//     No dangling symlinks are created.
//   - The staging HOME contains symlinks only. The generated git/ssh config
//     files (gitconfig, ssh-config, allowed_signers) live in the per-session
//     work dir (the staging HOME's parent — see PrepareSessionWorkDir in
//     session_work_dir.go, issue #2213) and are wired into the sandbox via
//     GIT_CONFIG_GLOBAL / GIT_SSH_COMMAND rather than via $HOME paths.
//
// Post-#2247 (Step 4 of #2132) the staging surface is reduced to the
// .ssh/* symlinks alone (Step 5 removes-wholesale scope). The chromium
// Library skeleton moved to the per-session work dir (the staging HOME's
// parent — see PrepareSessionWorkDir in session_work_dir.go), where
// CFFIXED_USER_HOME now points. Every other capability is delivered by an
// explicit SBPL grant on the real host path emitted by generateProfile —
// see sections 5, 5e, 5f, 5g, and 6a in sandbox_exec.go.
//
// Calling PrepareSandboxExecHome a second time on an existing staging dir is
// idempotent: existing symlinks are recreated (os.Symlink is preceded by
// os.Remove) and regular files are overwritten.
func (m *Manager) PrepareSandboxExecHome() (string, error) {
	stagingHome, err := m.sandboxExecHomePath()
	if err != nil {
		return "", err
	}

	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}

	// ── Create the staging HOME directory tree ────────────────────────────────
	// All subdirectories that will receive symlinks or generated files must
	// be created before we attempt to create entries inside them.
	dirs := []string{
		stagingHome,
		filepath.Join(stagingHome, ".ssh"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0o700); err != nil {
			return "", fmt.Errorf("container: sandbox-exec: create staging dir %s: %w", d, err)
		}
	}

	// ── Helper: create a symlink (idempotent) ─────────────────────────────────
	// Removes any existing entry at dst (file, symlink, or empty dir) before
	// creating the new symlink so that re-runs are idempotent.
	makeSymlink := func(src, dst string) error {
		_ = os.Remove(dst) // ignore error — may not exist
		return os.Symlink(src, dst)
	}

	// ── Helper: conditionally create symlink if source exists (os.Stat) ──────
	symlinkIfExists := func(src, dst string) {
		if _, err := os.Stat(src); err != nil {
			return // source does not exist — skip; no dangling symlinks
		}
		if err := makeSymlink(src, dst); err != nil {
			log.Printf("container: sandbox-exec: symlink %s → %s: %v", dst, src, err)
		}
	}

	// ── SSH keys ──────────────────────────────────────────────────────────────
	// Mirror bwrap's SSH-key staging (the EvalSymlinks block in
	// bwrap.go BuildArgs): mount at generic canonical names under $HOME/.ssh/.
	sshDir := filepath.Join(home, ".ssh")

	accessKeyName := m.cfg.SshAccessKeyName
	if accessKeyName == "" {
		accessKeyName = "prismatic-koi-ed25519"
	}
	// Use symlinkIfExists (not symlinkIfResolvable) for the access key so that
	// the staging HOME symlink points at the stable intermediate sops symlink
	// (~/.ssh/<accessKeyName>) rather than the fully-resolved sops temp path
	// (e.g. /private/var/folders/.../secrets.d/<N>/...).
	//
	// On Darwin, the access key is managed by sops-nix and its concrete path
	// rotates on every darwin-rebuild switch (secrets.d/<N>/ increments).
	// If the staging HOME symlink points at the fully-resolved concrete path,
	// it becomes dangling after rotation and SSH breaks inside the session
	// with "Couldn't load public key … No such file or directory" (issue #1573).
	//
	// With symlinkIfExists the chain is:
	//   <stagingHome>/.ssh/access-key
	//     → ~/.ssh/<accessKeyName>               (stable sops symlink)
	//     → /private/var/folders/.../secrets.d/<current>/...  (sops resolves this)
	//
	// The SBPL profile already grants (allow file-read* (subpath "/private/var/folders"))
	// so the sandbox can follow the chain to whatever secrets.d/<N> is current,
	// even after a rotation that occurred after session spawn.
	symlinkIfExists(
		filepath.Join(sshDir, accessKeyName),
		filepath.Join(stagingHome, ".ssh", "access-key"),
	)

	signingKeyName := m.cfg.SshSigningKeyName
	if signingKeyName == "" {
		signingKeyName = "prismatic-koi-ed25519-signingkey"
	}
	// Use symlinkIfExists (not symlinkIfResolvable) for signing keys so that
	// the staging HOME symlink points at the stable intermediate sops symlink
	// (~/.ssh/prismatic-koi-ed25519-signingkey{,.pub}) rather than the
	// fully-resolved sops temp path (e.g. /private/var/folders/.../secrets.d/271/).
	//
	// sops secrets rotate: on darwin-rebuild switch the secrets.d/<N> directory
	// increments. If the staging HOME symlink points at the fully-resolved
	// concrete path, it becomes dangling after rotation and git push fails with
	// "Couldn't load public key … No such file or directory" (issue #1410).
	//
	// With symlinkIfExists the chain is:
	//   <stagingHome>/.ssh/signing-key{,.pub}
	//     → ~/.ssh/prismatic-koi-ed25519-signingkey{,.pub}   (stable sops symlink)
	//     → /private/var/folders/.../secrets.d/<current>/... (sops resolves this)
	//
	// The SBPL profile already grants (allow file-read* (subpath "/private/var/folders"))
	// so the sandbox can follow the chain to whatever secrets.d/<N> is current,
	// even after a rotation that occurred after session spawn.
	//
	symlinkIfExists(
		filepath.Join(sshDir, signingKeyName),
		filepath.Join(stagingHome, ".ssh", "signing-key"),
	)
	symlinkIfExists(
		filepath.Join(sshDir, signingKeyName+".pub"),
		filepath.Join(stagingHome, ".ssh", "signing-key.pub"),
	)
	symlinkIfExists(
		filepath.Join(sshDir, "known_hosts"),
		filepath.Join(stagingHome, ".ssh", "known_hosts"),
	)
	symlinkIfExists(
		filepath.Join(sshDir, "allowed_signers"),
		filepath.Join(stagingHome, ".ssh", "allowed_signers"),
	)

	// Note (#2213): the generated ssh config is no longer written into the
	// staging HOME. It lives at <sessionDir>/ssh-config (see
	// writeSshConfigToDir in session_work_dir.go) and is passed to ssh via
	// -F in GIT_SSH_COMMAND. The .ssh/* symlinks above remain so existing
	// staging-HOME reads keep working until Step 5 of #2132 deletes them.

	// ── AWS ───────────────────────────────────────────────────────────────────
	// Note (#2234, Step 3a of #2132): the .aws/config and .aws/credentials
	// staging symlinks are no longer created. The aws CLI resolves both files
	// via the AWS_CONFIG_FILE / AWS_SHARED_CREDENTIALS_FILE env vars at the
	// host XDG paths (~/.config/aws/readonly-config and
	// ~/.config/aws/credentials). The in-sandbox read of the resolved sops
	// targets rides the broad (subpath "/private/var/folders") allow narrowed
	// by the #2211 secrets.d allowlist (collectSecretsDAllowlistNames derives
	// the exceptions from the same stable XDG source paths, so the read
	// survives sops rotations — #1410/#1573).
	//
	// Note (#2245, Step 3e of #2132): the .aws/sso and .aws/cli RW staging
	// symlinks are no longer created either (and no .aws/ staging dir exists).
	// The SDK-hardcoded ~/.aws/sso and ~/.aws/cli cache dirs are reached at
	// their real host paths via the §5 carve-out allows that generateProfile
	// emits after the broad ~/.aws deny — the carve-outs are now the sole
	// in-sandbox capability for those two subtrees. The broader ~/.aws
	// subtree stays denied.

	// ── Kube ──────────────────────────────────────────────────────────────────
	// Note (#2235, Step 3b of #2132): the .kube/config staging symlink is no
	// longer created (and no .kube/ staging dir exists). kubectl resolves the
	// config via the KUBECONFIG env var at the host XDG path
	// (~/.config/kube/agents-config); the in-sandbox read of the resolved sops
	// target rides the broad (subpath "/private/var/folders") allow narrowed
	// by the #2211 secrets.d allowlist (collectSecretsDAllowlistNames derives
	// the exception from the same stable XDG source path, so the read survives
	// sops rotations — #1410/#1573). kubectl's discovery/http cache is
	// redirected to <sessionDir>/kube-cache via KUBECACHEDIR (see
	// SessionWorkDirKubeEnv in session_work_dir.go).

	// ── prism agent role prompts (issue #2032) ─────────────────────────
	// Note (#2245, Step 3f of #2132): the .config/prism/agents staging symlink
	// is no longer created (and no .config/ staging dir exists).
	// generateProfile emits an explicit RO (subpath ~/.config/prism/agents)
	// grant on the real host path instead (section 5f).

	// ── Library/Application Support/Google + Library/Caches/Google ─────────
	// Note (#2247, Step 4 of #2132): the empty chromium Library skeleton dirs
	// are no longer created in the staging HOME. They live in the per-session
	// work dir (the staging HOME's parent — see SessionWorkDirChromiumDirs in
	// session_work_dir.go), which is where the dispatcher now points
	// CFFIXED_USER_HOME. Writes ride the existing (subpath <sessionDir>) RW
	// allow — no staging surface and no new SBPL rule.

	// ── Claude ────────────────────────────────────────────────────────────────
	// Note (#2243, Step 3c of #2132): the .claude write-through staging symlink
	// is no longer created. claude-code resolves its config dir (and
	// .claude.json) via the CLAUDE_CONFIG_DIR env var at the host XDG path
	// (~/.config/claude, declared in agent.envVars by the nix module).
	// Unlike the aws/kube XDG configs, ~/.config/claude is a plain host
	// directory — NOT a sops symlink — so the #2211 secrets.d allowlist is
	// not involved: the read/write capability comes from the explicit RW
	// (subpath ~/.config/claude) grant emitted by generateProfile.

	// ── .mcp-auth/, .npm/, .cache/ ──────────────────────────────────────────
	// Note (#2245, Step 3e of #2132): the RW staging symlinks for .mcp-auth/,
	// .npm/, .cache/bun, and .cache/nix are no longer created (and no .cache/
	// staging dir exists). generateProfile emits an explicit RW grant block on
	// the real host paths instead (section 5e). The consumers derive these
	// paths from $HOME / XDG_CACHE_HOME, which still point into the staging
	// HOME until Step 5 of #2132 flips them to the real home — interim writes
	// land ephemerally inside the staging HOME (covered by the session work
	// dir RW allow) and the real-path grants become load-bearing at Step 5.

	// ── .cache/prism/clipboard ────────────────────────────────────────────────
	// Note (#2245, Step 3f of #2132): the RO clipboard staging symlink is no
	// longer created. The host writes images to the real
	// ~/.cache/prism/clipboard and the agent reads them at that absolute path;
	// generateProfile emits an explicit RO grant on the real path (section 5f).

	// Note (#2213): the generated gitconfig is no longer written into the
	// staging HOME. It lives at <sessionDir>/gitconfig (see
	// writeGitconfigToDir in session_work_dir.go) and is wired in via
	// GIT_CONFIG_GLOBAL. The missing-git-identity hard error (#1960) is
	// preserved: PrepareSessionWorkDir fails Prepare before the session
	// starts (see sandboxExecIsolator.Prepare in lifecycle_dispatch.go).

	// ── .nix-profile ──────────────────────────────────────────────────────────
	// Note (#2245, Step 3f of #2132): the .nix-profile RO staging symlink is
	// no longer created. ~/.nix-profile is itself a symlink on the host;
	// generateProfile emits an RO literal allow on the symlink node plus an RO
	// rule on its EvalSymlinks-resolved target (section 5g).

	// ── PI Atlassian MCP OAuth token (Step 3d of #2132, issue #2245) ─────────
	// The dedicated touch-and-symlink staging step for
	// ~/.pi/agent/atlassian-mcp-oauth.json (former stagePIOAuthToken, issue
	// #1597) is gone. The capability collapses into the existing pi-gated RW
	// (subpath ~/.pi/agent) grant (section 6a): the Atlassian MCP extension
	// creates the file itself at the real path once $HOME resolution lands on
	// the real home (Step 5 of #2132). Until then, in-sandbox homedir()-based
	// writes land ephemerally inside the staging HOME (the extension's
	// mkdirSync({recursive: true}) creates .pi/agent under the session work
	// dir RW allow) — no host-side touch is needed for either window.

	return stagingHome, nil
}

// SandboxExecHomePath is the exported version of sandboxExecHomePath. It
// returns the staging HOME path for this Manager's session/instance. Used by
// cmd/agent_run.go to override HOME in the env passed to syscall.Exec.
func (m *Manager) SandboxExecHomePath() (string, error) {
	return m.sandboxExecHomePath()
}

// SandboxExecStagingHomePath returns the staging HOME path for the given
// instance ID. This is an exported convenience for callers (e.g. cmd/cleanup.go)
// that have the instance_id but no Manager instance.
//
// Path: ~/.local/state/prism/sessions/<instanceID>/home/
func SandboxExecStagingHomePath(instanceID string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}
	if home == "" {
		return "", fmt.Errorf("container: sandbox-exec: cannot determine user home directory")
	}
	if instanceID == "" {
		return "", fmt.Errorf("container: sandbox-exec: instanceID is empty")
	}
	return filepath.Join(home, ".local", "state", "prism", "sessions", instanceID, "home"), nil
}

// RemoveSandboxExecStagingHome removes the staging HOME directory tree for the
// given instance ID. It is idempotent — calling it when the directory does not
// exist is a no-op.
//
// This is called from cmd/cleanup.go cleanup paths that have the instance_id
// (e.g. headlessCleanup, headlessCloseSession) to clean up the staging dir
// created by PrepareSandboxExecHome.
func RemoveSandboxExecStagingHome(instanceID string) {
	stagingHome, err := SandboxExecStagingHomePath(instanceID)
	if err != nil {
		return // can't derive path — nothing to do
	}
	_ = os.RemoveAll(stagingHome)
}

// StagingSymlinkTarget represents a resolved symlink target with metadata
// about whether the target is a directory (requiring subpath) or a file
// (allowing literal), and whether writes to the target must be allowed.
type StagingSymlinkTarget struct {
	// ResolvedPath is the resolved absolute path of the symlink target.
	ResolvedPath string
	// IsDir is true when the resolved target is a directory. Directory
	// targets require (subpath ...) rules in SBPL; file targets use (literal ...).
	IsDir bool
	// Writable is true when the sandbox must be allowed to write to this
	// target (and, for directories, its contents). Mirrors the bwrap --bind
	// (RW) vs --ro-bind (RO) distinction. Post-#2245 the staging surface is
	// .ssh/* only — all RO — so Writable is always false in practice; the
	// field is retained so the RW/RO emission split in generateProfile stays
	// shape-stable until Step 5 of #2132 deletes the whole mechanism.
	Writable bool
}

// collectStagingHomeSymlinkTargets resolves all symlinks in the staging HOME
// directory and returns the unique set of resolved real paths. These are the
// paths the SBPL profile must allow so the sandbox can read through the symlinks.
//
// The return value includes IsDir and Writable metadata so callers can emit
// the appropriate SBPL rules:
//   - Directory targets → (subpath ...) rules.
//   - File targets → (literal ...) rules.
//   - Writable targets → file-write* alongside file-read*; RO targets →
//     file-read* only.
//
// Post-#2245 (Steps 3d–3f of #2132) the only staging symlinks left are the
// .ssh/* entries, all read-only — every other category is delivered by an
// explicit grant on the real host path in generateProfile. All collected
// targets are therefore classified Writable=false.
//
// Symlink targets that fall under a path that will be denied by the profile
// (e.g. host $HOME/.aws) are excluded from the results to avoid the
// literal-over-subpath precedence issue in Apple's SBPL: a (literal ...) allow
// for a path inside a (subpath ...) deny region would defeat the deny.
//
// The traversal is shallow: only top-level symlinks in the staging HOME tree
// are followed. We do not recurse into symlinked directory contents.
func collectStagingHomeSymlinkTargets(stagingHome string) ([]StagingSymlinkTarget, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}

	// deniedPrefixes lists host paths that will be denied in the SBPL profile.
	// Symlink targets that fall under these prefixes are excluded from the
	// allow-literal/subpath block to avoid the literal-over-subpath precedence
	// issue in Apple's SBPL.
	//
	// Post-#2245 no staging symlink targets ~/.aws any more (the sso/cli
	// carve-out plumbing that used to live here moved entirely to the §5
	// profile rules), but the deny-prefix exclusion is kept as defence in
	// depth: if a future staging symlink ever resolves under ~/.aws, it must
	// not silently punch a literal allow through the deny.
	var deniedPrefixes []string
	if home != "" {
		deniedPrefixes = append(deniedPrefixes, filepath.Join(home, ".aws")+"/")
	}

	isDenied := func(path string) bool {
		for _, prefix := range deniedPrefixes {
			if strings.HasPrefix(path+"/", prefix) || path == strings.TrimSuffix(prefix, "/") {
				return true
			}
		}
		return false
	}

	seen := map[string]bool{}
	var targets []StagingSymlinkTarget

	// add resolves a symlink's raw target (the value of os.Readlink) and
	// appends it to targets. entryRelPath is the path of the symlink entry
	// relative to stagingHome, used to look up the Writable classification.
	add := func(rawTarget, entryRelPath string) {
		resolved, evalErr := filepath.EvalSymlinks(rawTarget)
		if evalErr != nil {
			return
		}
		if seen[resolved] {
			return
		}
		if isDenied(resolved) {
			// Exclude targets under denied paths to avoid defeating deny rules.
			return
		}
		seen[resolved] = true
		// Determine whether the target is a directory or a file.
		info, statErr := os.Stat(resolved)
		isDir := statErr == nil && info.IsDir()
		// Post-#2245 every remaining staging symlink (.ssh/*) is read-only;
		// the RW categories moved to explicit real-path grants in
		// generateProfile. entryRelPath is retained in the signature for
		// shape stability until Step 5 of #2132 deletes the collector.
		_ = entryRelPath
		targets = append(targets, StagingSymlinkTarget{
			ResolvedPath: resolved,
			IsDir:        isDir,
			Writable:     false,
		})
	}

	// Use os.ReadDir for the top-level staging HOME entries only (no recursion).
	// filepath.Walk doesn't follow symlinks, so a top-level walk would stop at
	// symlinks pointing at directories — which is the behaviour we want (don't
	// recurse into symlinked dirs). We use ReadDir instead for clarity.
	scanDir := func(dirRelPath string) {
		dir := filepath.Join(stagingHome, dirRelPath)
		entries, readErr := os.ReadDir(dir)
		if readErr != nil {
			return
		}
		for _, e := range entries {
			entryPath := filepath.Join(dir, e.Name())
			// Only process symlinks; regular files and real dirs are fine as-is.
			if e.Type()&os.ModeSymlink != 0 {
				linkTarget, readLinkErr := os.Readlink(entryPath)
				if readLinkErr != nil {
					continue
				}
				if !filepath.IsAbs(linkTarget) {
					linkTarget = filepath.Join(dir, linkTarget)
				}
				// Compute entry path relative to stagingHome for writable lookup.
				var relPath string
				if dirRelPath == "" {
					relPath = e.Name()
				} else {
					relPath = dirRelPath + "/" + e.Name()
				}
				add(linkTarget, relPath)
			}
		}
	}

	// Scan the top-level staging HOME and the .ssh subdirectory — the only
	// staging surface left post-#2247 (the chromium Library skeleton moved to
	// the per-session work dir in Step 4 of #2132).
	scanDir("")
	scanDir(".ssh")

	return targets, nil
}
