//go:build darwin

package container

// Integration tests for the (version 3) sandbox-exec profile generated by
// generateProfile(). These tests invoke /usr/bin/sandbox-exec directly with
// the generated profile and verify that positive cases succeed and negative
// cases remain denied. Build tag: darwin (skipped on Linux).
//
// These tests are the seed pattern for the broader integration-test convention
// tracked in #1192. The wider withMutatedProfile helper and paired negative
// tests for every rule will be codified in that follow-up.
//
// Requirements: #1200 (AC block — integration tests section).

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// writeProfileForIntegration writes the generated profile for the given
// manager to a temp file and returns its path. The caller is responsible for
// removing the file.
func writeProfileForIntegration(t *testing.T, m *Manager) string {
	t.Helper()
	profileContent := generateProfile(m)
	f, err := os.CreateTemp(t.TempDir(), "sandbox-profile-*.sb")
	if err != nil {
		t.Fatalf("create temp profile file: %v", err)
	}
	defer f.Close()
	if _, err := f.WriteString(profileContent); err != nil {
		t.Fatalf("write profile: %v", err)
	}
	return f.Name()
}

// runUnderSandbox runs the given command under /usr/bin/sandbox-exec with the
// given profile and returns the combined stdout+stderr output and the exit
// code. It never fatally fails — callers assert on the returned values.
func runUnderSandbox(t *testing.T, profilePath string, env []string, args ...string) (output string, exitCode int) {
	t.Helper()
	cmdArgs := append([]string{"-f", profilePath}, args...)
	cmd := exec.Command("/usr/bin/sandbox-exec", cmdArgs...)
	if len(env) > 0 {
		cmd.Env = env
	}
	out, err := cmd.CombinedOutput()
	output = string(out)
	exitCode = 0
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		} else {
			// Command failed to start — treat as exit code -1.
			exitCode = -1
		}
	}
	return output, exitCode
}

// sandboxExecAvailable returns true if /usr/bin/sandbox-exec exists.
// Tests skip gracefully if it is absent (e.g. in a CI environment without
// the full macOS toolchain).
func sandboxExecAvailable() bool {
	_, err := os.Stat("/usr/bin/sandbox-exec")
	return err == nil
}

// newIntegrationManager returns a Manager wired up with a sandboxExecIsolator
// for integration tests. The returned stagingHome is the path embedded into
// the generated profile (from sandboxExecHomePath), which is what must be
// used as HOME in the sandbox environment.
func newIntegrationManager(t *testing.T) (*Manager, string) {
	t.Helper()
	// We use a fake worktree so the RW allow covers a real path that exists.
	worktree := t.TempDir()
	m := newSandboxExecManager(Config{
		SessionName: "integration-test@main",
		Worktree:    worktree,
		InstanceID:  "integration-test",
	})
	// Use the profile's own staging home path so HOME in the sandbox matches
	// what the profile allows. Ensures that git/ssh can read the home dir.
	stagingHome := profileStagingHome(t, m)
	return m, stagingHome
}

// baseEnv returns a minimal environment for sandbox-exec test invocations.
// We pass PATH (required for binary lookup), HOME pointing at the staging dir
// used by the profile (from sandboxExecHomePath), and DEVELOPER_DIR set to the
// CommandLineTools location so that /usr/bin/git does not fail due to an absent
// /var/select/developer_dir symlink.
//
// GIT_CONFIG_NOSYSTEM=1 prevents /usr/bin/git from reading /etc/gitconfig.
// GIT_CONFIG_GLOBAL=/dev/null prevents git from reading $HOME/.config/git/config
// or $HOME/.gitconfig, avoiding a write-permission failure on the staging home
// when the profile only grants read access to the var/folders TMPDIR subtree.
func baseEnv(stagingHome string) []string {
	return []string{
		"PATH=" + os.Getenv("PATH"),
		"HOME=" + stagingHome,
		"DEVELOPER_DIR=/Library/Developer/CommandLineTools",
		"GIT_CONFIG_NOSYSTEM=1",
		"GIT_CONFIG_GLOBAL=/dev/null",
	}
}

// profileStagingHome returns the staging HOME path that generateProfile will
// embed into the profile for the given manager. This is the path that must be
// used as HOME in the sandbox environment so git and other tools can access it.
//
// If the home directory cannot be created (e.g. in a nix build sandbox where
// HOME=/homeless-shelter is a read-only filesystem), the test is skipped.
func profileStagingHome(t *testing.T, m *Manager) string {
	t.Helper()
	path, err := m.sandboxExecHomePath()
	if err != nil {
		t.Skipf("sandboxExecHomePath unavailable (likely build sandbox): %v", err)
	}
	// Ensure the directory exists so programs that probe it succeed.
	if err := os.MkdirAll(path, 0o755); err != nil {
		t.Skipf("mkdir staging home %s: %v (likely read-only build sandbox — skipping integration test)", path, err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(path) })
	return path
}

// ── Positive cases ────────────────────────────────────────────────────────────

// TestSandboxExecIntegration_EchoHi verifies that /bin/echo hi exits 0 under
// the v3 profile (P1 in F.1 §3.1).
func TestSandboxExecIntegration_EchoHi(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)

	out, code := runUnderSandbox(t, profilePath, baseEnv(stagingHome), "/bin/echo", "hi")
	if code != 0 {
		t.Errorf("/bin/echo hi: want exit 0, got %d\noutput: %s", code, out)
	}
	if !strings.Contains(out, "hi") {
		t.Errorf("/bin/echo hi: expected 'hi' in output; got: %q", out)
	}
}

// TestSandboxExecIntegration_LsEtcHosts verifies that /bin/ls /etc/hosts
// exits 0 under the v3 profile (P2 in F.1 §3.1).
func TestSandboxExecIntegration_LsEtcHosts(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)

	out, code := runUnderSandbox(t, profilePath, baseEnv(stagingHome), "/bin/ls", "/etc/hosts")
	if code != 0 {
		t.Errorf("/bin/ls /etc/hosts: want exit 0, got %d\noutput: %s", code, out)
	}
}

// TestSandboxExecIntegration_CatEtcHosts verifies that /bin/cat /etc/hosts
// exits 0 and prints the hosts file content under the v3 profile (P3 in F.1 §3.1).
func TestSandboxExecIntegration_CatEtcHosts(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)

	out, code := runUnderSandbox(t, profilePath, baseEnv(stagingHome), "/bin/cat", "/etc/hosts")
	if code != 0 {
		t.Errorf("/bin/cat /etc/hosts: want exit 0, got %d\noutput: %s", code, out)
	}
	// The hosts file should contain "localhost" on any macOS system.
	if !strings.Contains(out, "localhost") {
		t.Errorf("/bin/cat /etc/hosts: expected 'localhost' in output; got: %q", out)
	}
}

// TestSandboxExecIntegration_GitVersion verifies that /usr/bin/git --version
// exits 0 under the v3 profile (P4 in F.1 §3.1). xcrun cache-write errors
// on stderr are acceptable (non-fatal, SIP-related per F.1 §4.4).
// On hosts where /var/select/developer_dir is absent, DEVELOPER_DIR is set
// to /Library/Developer/CommandLineTools via baseEnv.
func TestSandboxExecIntegration_GitVersion(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	if _, err := os.Stat("/usr/bin/git"); err != nil {
		t.Skip("/usr/bin/git not present")
	}
	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)

	out, code := runUnderSandbox(t, profilePath, baseEnv(stagingHome), "/usr/bin/git", "--version")
	if code != 0 {
		t.Errorf("/usr/bin/git --version: want exit 0, got %d\noutput: %s", code, out)
	}
	if !strings.Contains(out, "git version") {
		t.Errorf("/usr/bin/git --version: expected 'git version' in output; got: %q", out)
	}
}

// TestSandboxExecIntegration_UnameDashA verifies that /usr/bin/uname -a exits
// 0 and prints the Darwin uname line under the v3 profile (P5 in F.1 §3.1).
func TestSandboxExecIntegration_UnameDashA(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)

	out, code := runUnderSandbox(t, profilePath, baseEnv(stagingHome), "/usr/bin/uname", "-a")
	if code != 0 {
		t.Errorf("/usr/bin/uname -a: want exit 0, got %d\noutput: %s", code, out)
	}
	if !strings.Contains(out, "Darwin") {
		t.Errorf("/usr/bin/uname -a: expected 'Darwin' in output; got: %q", out)
	}
}

// TestSandboxExecIntegration_WhichOpencode verifies that /usr/bin/which
// opencode exits 0 under the v3 profile (P6 in F.1 §3.1).
func TestSandboxExecIntegration_WhichOpencode(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	// Only run this test if opencode is resolvable in PATH.
	whichOut, err := exec.Command("/usr/bin/which", "opencode").Output()
	if err != nil || strings.TrimSpace(string(whichOut)) == "" {
		t.Skip("opencode not in PATH — skipping which test")
	}
	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)

	out, code := runUnderSandbox(t, profilePath, baseEnv(stagingHome), "/usr/bin/which", "opencode")
	if code != 0 {
		t.Errorf("/usr/bin/which opencode: want exit 0, got %d\noutput: %s", code, out)
	}
	if strings.TrimSpace(out) == "" {
		t.Errorf("/usr/bin/which opencode: expected non-empty output (resolved path); got empty")
	}
}

// TestSandboxExecIntegration_SSHVersion verifies that /usr/bin/ssh -V exits
// 0 and prints the OpenSSH version string under the v3 profile (P7 in F.1 §3.1).
func TestSandboxExecIntegration_SSHVersion(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	if _, err := os.Stat("/usr/bin/ssh"); err != nil {
		t.Skip("/usr/bin/ssh not present")
	}
	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)

	out, code := runUnderSandbox(t, profilePath, baseEnv(stagingHome), "/usr/bin/ssh", "-V")
	if code != 0 {
		t.Errorf("/usr/bin/ssh -V: want exit 0, got %d\noutput: %s", code, out)
	}
	// ssh -V prints to stderr; combined output captured.
	if !strings.Contains(out, "OpenSSH") {
		t.Errorf("/usr/bin/ssh -V: expected 'OpenSSH' in output; got: %q", out)
	}
}

// TestSandboxExecIntegration_OpencodeNoSIGABRT verifies that the opencode
// harness exits without SIGABRT under the v3 profile (P8 in F.1 §3.1).
// Exit 0 or any non-SIGABRT exit code is acceptable — "unexpected error"
// from a missing server is fine. SIGABRT (exit code 134 on Darwin) is not.
func TestSandboxExecIntegration_OpencodeNoSIGABRT(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	// Find opencode in PATH.
	opencodePath, err := exec.LookPath("opencode")
	if err != nil || opencodePath == "" {
		t.Skip("opencode not in PATH — skipping opencode SIGABRT test")
	}
	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)

	_, code := runUnderSandbox(t, profilePath, baseEnv(stagingHome), opencodePath, "--help")
	// SIGABRT = signal 6, which becomes exit code 134 on Darwin (128+6).
	const sigabrtExit = 134
	if code == sigabrtExit {
		t.Errorf("opencode --help: exited with SIGABRT (exit code %d) under v3 profile — the dyld fix is not working", code)
	}
}

// TestSandboxExecIntegration_NixBashEchoHi verifies that a Nix-built bash
// exits 0 and prints "hi" under the v3 profile (P9 in F.1 §3.1).
func TestSandboxExecIntegration_NixBashEchoHi(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	// Find bash via PATH — on a Nix host this will resolve to a Nix store path.
	bashPath, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash not in PATH")
	}
	// Only run this test if bash is from the Nix store.
	if !strings.HasPrefix(bashPath, "/nix/store/") {
		t.Skipf("bash at %q is not Nix-built — skipping Nix bash test", bashPath)
	}
	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)

	out, code := runUnderSandbox(t, profilePath, baseEnv(stagingHome), bashPath, "-c", "echo hi")
	if code != 0 {
		t.Errorf("Nix bash -c 'echo hi': want exit 0, got %d\noutput: %s", code, out)
	}
	if !strings.Contains(out, "hi") {
		t.Errorf("Nix bash -c 'echo hi': expected 'hi' in output; got: %q", out)
	}
}

// ── Negative cases ────────────────────────────────────────────────────────────

// TestSandboxExecIntegration_SSHKeyDenied verifies that an SSH private key in
// the host home directory is NOT readable from inside the sandbox (N1 in
// F.1 §3.2). Uses a real (or dummy) key file.
func TestSandboxExecIntegration_SSHKeyDenied(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	realHome, err := os.UserHomeDir()
	if err != nil {
		t.Skip("cannot determine home directory")
	}

	// Prefer a real key if it exists; otherwise create a dummy file in a
	// temp location that is NOT the staging home (so it is denied).
	sshKeyPath := filepath.Join(realHome, ".ssh", "id_ed25519")
	if _, err := os.Stat(sshKeyPath); err != nil {
		// Create a dummy key file outside the staging HOME.
		tmpKey := filepath.Join(t.TempDir(), "dummy_key")
		if err := os.WriteFile(tmpKey, []byte("dummy ssh key"), 0o600); err != nil {
			t.Fatalf("create dummy key: %v", err)
		}
		sshKeyPath = tmpKey
	}

	m, stagingHome := newIntegrationManager(t)
	env := baseEnv(stagingHome)
	// Set HOME to the real home so the deny rule for ~/.aws is exercised with
	// the real path; the staging home is a separate temp dir.
	for i, kv := range env {
		if strings.HasPrefix(kv, "HOME=") {
			env[i] = "HOME=" + realHome
		}
	}
	// Re-generate profile with the real home so the deny covers the right path.
	realM := newSandboxExecManager(Config{
		SessionName: "integration-test@main",
		Worktree:    m.cfg.Worktree,
		InstanceID:  "integration-test",
	})
	realProfilePath := writeProfileForIntegration(t, realM)

	out, code := runUnderSandbox(t, realProfilePath, env, "/bin/cat", sshKeyPath)
	if code == 0 {
		t.Errorf("cat SSH key: expected non-zero exit (denied), got exit 0\noutput: %s", out)
	}
	if !strings.Contains(out, "Operation not permitted") && !strings.Contains(out, "Permission denied") {
		t.Errorf("cat SSH key: expected 'Operation not permitted' in output; got: %q", out)
	}
}

// TestSandboxExecIntegration_AWSCredentialsDenied verifies that the host
// ~/.aws/credentials is NOT readable from inside the sandbox (N2 in F.1 §3.2).
func TestSandboxExecIntegration_AWSCredentialsDenied(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	realHome, err := os.UserHomeDir()
	if err != nil {
		t.Skip("cannot determine home directory")
	}

	awsCredPath := filepath.Join(realHome, ".aws", "credentials")
	if _, err := os.Stat(awsCredPath); err != nil {
		// Create a dummy credentials file so we have something to try to read.
		awsDir := filepath.Join(t.TempDir(), ".aws")
		if err := os.MkdirAll(awsDir, 0o755); err != nil {
			t.Fatalf("create dummy .aws dir: %v", err)
		}
		awsCredPath = filepath.Join(awsDir, "credentials")
		if err := os.WriteFile(awsCredPath, []byte("[default]\naws_access_key_id=DUMMY"), 0o600); err != nil {
			t.Fatalf("create dummy credentials: %v", err)
		}
		// Use a manager that denies this specific path.
		m := newSandboxExecManager(Config{
			SessionName: "integration-test@main",
			Worktree:    t.TempDir(),
			InstanceID:  "integration-test",
		})
		// Override the home to point at our temp dir's parent so the deny covers awsDir.
		t.Setenv("HOME", filepath.Dir(awsDir))
		profilePath := writeProfileForIntegration(t, m)
		stagingHome := filepath.Join(t.TempDir(), "staging-home")
		if err := os.MkdirAll(stagingHome, 0o755); err != nil {
			t.Fatalf("mkdir staging home: %v", err)
		}
		env := baseEnv(stagingHome)
		out, code := runUnderSandbox(t, profilePath, env, "/bin/cat", awsCredPath)
		if code == 0 {
			t.Errorf("cat AWS credentials (dummy): expected non-zero exit, got 0\noutput: %s", out)
		}
		return
	}

	// Real ~/.aws/credentials exists — use the real home in the manager.
	m, stagingHome := newIntegrationManager(t)
	env := baseEnv(stagingHome)
	// Pass the real HOME so the deny rule is generated for ~/.aws.
	for i, kv := range env {
		if strings.HasPrefix(kv, "HOME=") {
			env[i] = "HOME=" + realHome
		}
	}
	realM := newSandboxExecManager(Config{
		SessionName: "integration-test@main",
		Worktree:    m.cfg.Worktree,
		InstanceID:  "integration-test",
	})
	realProfilePath := writeProfileForIntegration(t, realM)

	out, code := runUnderSandbox(t, realProfilePath, env, "/bin/cat", awsCredPath)
	if code == 0 {
		t.Errorf("cat ~/.aws/credentials: expected non-zero exit (denied), got exit 0\noutput: %s", out)
	}
	if !strings.Contains(out, "Operation not permitted") && !strings.Contains(out, "Permission denied") {
		t.Errorf("cat ~/.aws/credentials: expected 'Operation not permitted' in output; got: %q", out)
	}
}

// TestSandboxExecIntegration_HomeCodeDirectoryDenied verifies that the host
// ~/code directory is NOT accessible from inside the sandbox (N3 in F.1 §3.2).
func TestSandboxExecIntegration_HomeCodeDirectoryDenied(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	realHome, err := os.UserHomeDir()
	if err != nil {
		t.Skip("cannot determine home directory")
	}
	codeDir := filepath.Join(realHome, "code")
	if _, err := os.Stat(codeDir); err != nil {
		t.Skipf("~/code does not exist on this host — skipping: %v", err)
	}

	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)
	env := baseEnv(stagingHome)

	// find ~/code -name '.env' — should produce no results (directory is inaccessible).
	// Note: find exits 0 even when the root path is denied (operation not permitted
	// on the root argument). We just assert no .env files were found.
	out, _ := runUnderSandbox(t, profilePath, env, "/usr/bin/find", codeDir, "-name", ".env")
	// The output should be empty or contain only the "Operation not permitted" error.
	// We assert that no actual .env file paths appear in the output.
	lines := strings.Split(strings.TrimSpace(out), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if strings.HasSuffix(line, ".env") {
			t.Errorf("find ~/code -name .env returned .env file %q — host source tree should be inaccessible", line)
		}
	}
}

// TestSandboxExecIntegration_KeychainDenied verifies that the host
// ~/Library/Keychains/login.keychain-db is NOT readable from inside the
// sandbox (N4 in F.1 §3.2).
func TestSandboxExecIntegration_KeychainDenied(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	realHome, err := os.UserHomeDir()
	if err != nil {
		t.Skip("cannot determine home directory")
	}
	keychainPath := filepath.Join(realHome, "Library", "Keychains", "login.keychain-db")
	if _, err := os.Stat(keychainPath); err != nil {
		t.Skipf("login.keychain-db does not exist — skipping: %v", err)
	}

	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)
	env := baseEnv(stagingHome)

	out, code := runUnderSandbox(t, profilePath, env, "/bin/cat", keychainPath)
	if code == 0 {
		t.Errorf("cat login.keychain-db: expected non-zero exit (denied), got exit 0\noutput: %s", out)
	}
	if !strings.Contains(out, "Operation not permitted") && !strings.Contains(out, "Permission denied") {
		t.Errorf("cat login.keychain-db: expected 'Operation not permitted' in output; got: %q", out)
	}
}

// TestSandboxExecIntegration_DocumentsDenied verifies that a file under
// ~/Documents is NOT readable from inside the sandbox (N5 in F.1 §3.2).
func TestSandboxExecIntegration_DocumentsDenied(t *testing.T) {
	if !sandboxExecAvailable() {
		t.Skip("sandbox-exec not available")
	}
	realHome, err := os.UserHomeDir()
	if err != nil {
		t.Skip("cannot determine home directory")
	}
	// Create a sentinel file in a temp dir that we treat as the Documents test.
	// We don't need the file to really be in ~/Documents — any host-home path
	// that isn't the staging home or worktree should be denied.
	// Use ~/Documents if it exists; otherwise create a temp file in the real home.
	docsDir := filepath.Join(realHome, "Documents")
	var testFilePath string
	if _, err := os.Stat(docsDir); err == nil {
		// Create a file inside Documents for the test.
		testFilePath = filepath.Join(docsDir, "sandbox-exec-test-sentinel.txt")
		if wErr := os.WriteFile(testFilePath, []byte("sentinel"), 0o644); wErr != nil {
			// Can't write to Documents — use a different approach.
			testFilePath = ""
		} else {
			defer os.Remove(testFilePath)
		}
	}
	if testFilePath == "" {
		// Fall back: create a file directly in the real home (not staging, not worktree).
		testFilePath = filepath.Join(realHome, ".sandbox-exec-test-sentinel.txt")
		if wErr := os.WriteFile(testFilePath, []byte("sentinel"), 0o644); wErr != nil {
			t.Skipf("cannot create test sentinel file in home: %v", wErr)
		}
		defer os.Remove(testFilePath)
	}

	m, stagingHome := newIntegrationManager(t)
	profilePath := writeProfileForIntegration(t, m)
	env := baseEnv(stagingHome)

	out, code := runUnderSandbox(t, profilePath, env, "/bin/cat", testFilePath)
	if code == 0 {
		t.Errorf("cat %s: expected non-zero exit (denied), got exit 0\noutput: %s", testFilePath, out)
	}
	if !strings.Contains(out, "Operation not permitted") && !strings.Contains(out, "Permission denied") {
		t.Errorf("cat %s: expected 'Operation not permitted' in output; got: %q", testFilePath, out)
	}
}
