package container

// sandbox_exec_home.go — per-session staging HOME builder for sandbox-exec mode.
//
// PrepareSandboxExecHome populates a staging HOME directory at
// ~/.local/state/prism/sessions/<instance_id>/home/ with symlinks to the real
// credential, config, and cache paths the agent needs. The SBPL profile grants
// read access to every resolved symlink target, while the staging HOME itself
// is writable so the sandbox can do things like write to ~/.cache/opencode
// inside it (which symlinks through to the host path).
//
// Design decisions locked by the coordinator in issue #1017:
//
//  1. .claude/ is a symlink to host ~/.claude (matches bwrap's RW treatment at
//     bwrap.go:306-308). Writes to .credentials.json (e.g. token refreshes)
//     flow through the symlink to the host's ~/.claude/.credentials.json.
//  2. Library/Keychains/login.keychain-db is symlinked so that opencode-claude-auth
//     (which uses `security dump-keychain` with $HOME to find the keychain search
//     list) can locate the user's login keychain. The SBPL profile grants
//     file-read* on the resolved path via (literal login.keychain-db) (#1487).
//
//  2. .config/prism/agents/ is symlinked into the staging HOME for ALL roles
//     (including review-*) so the prism PI extension can read <role>.md at
//     before_agent_start. The dir is pure markdown with no secrets, so the
//     former review-prefix exclusion was dropped (issue #2032; design #2031).
//
//  3. .cache/nix/ is included as an RW symlink to ~/.cache/nix (matches bwrap
//     unconditional RW bind at bwrap.go:333-335).

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// sandboxExecHomePath returns the staging HOME path for the given instance ID.
// The path is:
//
//	~/.local/state/prism/sessions/<instance_id>/home/
//
// This is the per-session staging HOME that PrepareSandboxExecHome creates and
// populates with symlinks. InstanceID is used as the namespace key so concurrent
// sessions have independent staging dirs.
func (m *Manager) sandboxExecHomePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}
	if home == "" {
		return "", fmt.Errorf("container: sandbox-exec: cannot determine user home directory")
	}
	instanceID := m.cfg.InstanceID
	if instanceID == "" {
		// Fall back to session name when InstanceID is not set (e.g. tests
		// that construct Manager directly without a full spawn lifecycle).
		// Use the container name (slugified session name) to stay safe for
		// filesystem use.
		instanceID = m.name
	}
	return filepath.Join(home, ".local", "state", "prism", "sessions", instanceID, "home"), nil
}

// PrepareSandboxExecHome creates the per-session staging HOME directory and
// populates it with symlinks to the real credential, config, and cache paths
// that the agent needs. Returns the absolute path to the staging HOME.
//
// The staging HOME layout mirrors the bwrap sandbox home layout (every path
// that bwrap creates via bind-mount, sandbox-exec achieves via a symlink). The
// SBPL profile generated by generateProfile grants read access to every resolved
// symlink target so the sandbox can traverse the symlinks.
//
// Rules:
//   - When a source path does not exist on the host, the symlink is skipped.
//     No dangling symlinks are created.
//   - Generated regular files (.gitconfig, .ssh/config, opencode.json) are
//     written as regular files, not symlinks.
//   - .cache/nix/ is always included as an RW symlink to ~/.cache/nix.
//   - .config/prism/agents/ is symlinked in for ALL roles (including review-*)
//     so the PI extension can read <role>.md (issue #2032). The former
//     review-prefix exclusion was dropped — the dir is pure markdown with no
//     secrets, so there is no isolation value in hiding sibling role prompts.
//   - .claude/ is a symlink to host ~/.claude with a comment explaining the
//     Darwin write-through behaviour.
//
// Calling PrepareSandboxExecHome a second time on an existing staging dir is
// idempotent: existing symlinks are recreated (os.Symlink is preceded by
// os.Remove) and regular files are overwritten.
func (m *Manager) PrepareSandboxExecHome() (string, error) {
	stagingHome, err := m.sandboxExecHomePath()
	if err != nil {
		return "", err
	}

	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}

	// ── Create the staging HOME directory tree ────────────────────────────────
	// All subdirectories that will receive symlinks or generated files must
	// be created before we attempt to create entries inside them.
	dirs := []string{
		stagingHome,
		filepath.Join(stagingHome, ".ssh"),
		filepath.Join(stagingHome, ".aws"),
		filepath.Join(stagingHome, ".kube"),
		filepath.Join(stagingHome, ".cache"),
		filepath.Join(stagingHome, ".pi"),
		filepath.Join(stagingHome, ".config", "prism"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0o700); err != nil {
			return "", fmt.Errorf("container: sandbox-exec: create staging dir %s: %w", d, err)
		}
	}

	// ── Helper: create a symlink (idempotent) ─────────────────────────────────
	// Removes any existing entry at dst (file, symlink, or empty dir) before
	// creating the new symlink so that re-runs are idempotent.
	makeSymlink := func(src, dst string) error {
		_ = os.Remove(dst) // ignore error — may not exist
		return os.Symlink(src, dst)
	}

	// ── Helper: conditionally create symlink if source exists (os.Stat) ──────
	symlinkIfExists := func(src, dst string) {
		if _, err := os.Stat(src); err != nil {
			return // source does not exist — skip; no dangling symlinks
		}
		if err := makeSymlink(src, dst); err != nil {
			log.Printf("container: sandbox-exec: symlink %s → %s: %v", dst, src, err)
		}
	}

	// ── SSH keys ──────────────────────────────────────────────────────────────
	// Mirror bwrap.go:369-388: resolve via EvalSymlinks and mount at generic
	// canonical names under $HOME/.ssh/.
	sshDir := filepath.Join(home, ".ssh")

	accessKeyName := m.cfg.SshAccessKeyName
	if accessKeyName == "" {
		accessKeyName = "prismatic-koi-ed25519"
	}
	// Use symlinkIfExists (not symlinkIfResolvable) for the access key so that
	// the staging HOME symlink points at the stable intermediate sops symlink
	// (~/.ssh/<accessKeyName>) rather than the fully-resolved sops temp path
	// (e.g. /private/var/folders/.../secrets.d/<N>/...).
	//
	// On Darwin, the access key is managed by sops-nix and its concrete path
	// rotates on every darwin-rebuild switch (secrets.d/<N>/ increments).
	// If the staging HOME symlink points at the fully-resolved concrete path,
	// it becomes dangling after rotation and SSH breaks inside the session
	// with "Couldn't load public key … No such file or directory" (issue #1573).
	//
	// With symlinkIfExists the chain is:
	//   <stagingHome>/.ssh/access-key
	//     → ~/.ssh/<accessKeyName>               (stable sops symlink)
	//     → /private/var/folders/.../secrets.d/<current>/...  (sops resolves this)
	//
	// The SBPL profile already grants (allow file-read* (subpath "/private/var/folders"))
	// so the sandbox can follow the chain to whatever secrets.d/<N> is current,
	// even after a rotation that occurred after session spawn.
	symlinkIfExists(
		filepath.Join(sshDir, accessKeyName),
		filepath.Join(stagingHome, ".ssh", "access-key"),
	)

	signingKeyName := m.cfg.SshSigningKeyName
	if signingKeyName == "" {
		signingKeyName = "prismatic-koi-ed25519-signingkey"
	}
	// Use symlinkIfExists (not symlinkIfResolvable) for signing keys so that
	// the staging HOME symlink points at the stable intermediate sops symlink
	// (~/.ssh/prismatic-koi-ed25519-signingkey{,.pub}) rather than the
	// fully-resolved sops temp path (e.g. /private/var/folders/.../secrets.d/271/).
	//
	// sops secrets rotate: on darwin-rebuild switch the secrets.d/<N> directory
	// increments. If the staging HOME symlink points at the fully-resolved
	// concrete path, it becomes dangling after rotation and git push fails with
	// "Couldn't load public key … No such file or directory" (issue #1410).
	//
	// With symlinkIfExists the chain is:
	//   <stagingHome>/.ssh/signing-key{,.pub}
	//     → ~/.ssh/prismatic-koi-ed25519-signingkey{,.pub}   (stable sops symlink)
	//     → /private/var/folders/.../secrets.d/<current>/... (sops resolves this)
	//
	// The SBPL profile already grants (allow file-read* (subpath "/private/var/folders"))
	// so the sandbox can follow the chain to whatever secrets.d/<N> is current,
	// even after a rotation that occurred after session spawn.
	//
	symlinkIfExists(
		filepath.Join(sshDir, signingKeyName),
		filepath.Join(stagingHome, ".ssh", "signing-key"),
	)
	symlinkIfExists(
		filepath.Join(sshDir, signingKeyName+".pub"),
		filepath.Join(stagingHome, ".ssh", "signing-key.pub"),
	)
	symlinkIfExists(
		filepath.Join(sshDir, "known_hosts"),
		filepath.Join(stagingHome, ".ssh", "known_hosts"),
	)
	symlinkIfExists(
		filepath.Join(sshDir, "allowed_signers"),
		filepath.Join(stagingHome, ".ssh", "allowed_signers"),
	)

	// .ssh/config — regular generated file (not a symlink), using staging HOME
	// as the in-sandbox $HOME prefix so IdentityFile resolves correctly.
	if err := m.writeSshConfigToDir(stagingHome); err != nil {
		log.Printf("container: sandbox-exec: write staging .ssh/config: %v", err)
	}

	// ── AWS ───────────────────────────────────────────────────────────────────
	// Use symlinkIfExists (not symlinkIfResolvable) for the config and
	// credentials files so the staging HOME symlinks point at the stable
	// intermediate sops symlinks rather than the fully-resolved concrete path
	// inside secrets.d/<N>/. On Darwin, darwin-rebuild switch rotates
	// secrets.d/<N>/ → secrets.d/<N+1>/, invalidating any staging symlink
	// that captured the old concrete path (issue #1573).
	//
	// The SBPL profile already grants (allow file-read* (subpath "/private/var/folders"))
	// so the sandbox can follow the chain through whatever secrets.d/<current>
	// is live at read time.
	symlinkIfExists(
		filepath.Join(home, ".config", "aws", "readonly-config"),
		filepath.Join(stagingHome, ".aws", "config"),
	)
	symlinkIfExists(
		filepath.Join(home, ".config", "aws", "credentials"),
		filepath.Join(stagingHome, ".aws", "credentials"),
	)
	symlinkIfExists(
		filepath.Join(home, ".aws", "sso"),
		filepath.Join(stagingHome, ".aws", "sso"),
	)
	symlinkIfExists(
		filepath.Join(home, ".aws", "cli"),
		filepath.Join(stagingHome, ".aws", "cli"),
	)

	// ── Kube ──────────────────────────────────────────────────────────────────
	// Use symlinkIfExists (not symlinkIfResolvable) so the staging symlink
	// points at the stable intermediate (~/.config/kube/agents-config) rather
	// than the fully-resolved sops concrete path that rotates on each
	// darwin-rebuild switch (issue #1573).
	// ── prism agent role prompts (issue #2032) ─────────────────────────
	// Symlink ~/.config/prism/agents (deployed by pi.nix) into the staging
	// HOME at the canonical XDG path so the prism PI extension can read
	// <role>.md at before_agent_start. Included for ALL roles, including
	// review-* — the dir is pure markdown with no secrets (locked decision on
	// design #2031). collectStagingHomeSymlinkTargets scans .config/prism and
	// emits the SBPL read-allow for the resolved target, so no manual
	// generateProfile rule is needed.
	symlinkIfExists(
		filepath.Join(home, ".config", "prism", "agents"),
		filepath.Join(stagingHome, ".config", "prism", "agents"),
	)

	symlinkIfExists(
		filepath.Join(home, ".config", "kube", "agents-config"),
		filepath.Join(stagingHome, ".kube", "config"),
	)

	// ── Library/Application Support/Google + Library/Caches/Google (issue #2021) ─
	// playwright-cli launches the Nix-built `Google Chrome for Testing` binary
	// (chromium). Chromium reads NSHomeDirectory() (which the sandbox-exec
	// dispatch in agent_run_sandbox_exec_darwin.go redirects to stagingHome via
	// CFFIXED_USER_HOME) and writes its crash database, code cache, profile, and
	// SingletonLock under <home>/Library/Application Support/Google/Chrome for
	// Testing/ and <home>/Library/Caches/Google/Chrome for Testing/.
	//
	// We create empty, writable Google/ subdirectories under the staging Library
	// so chromium has somewhere to land its writes. We deliberately do NOT
	// symlink to the real ~/Library/Application Support/Google/ on the host —
	// that path holds the daily-driver Chrome's profile (cookies, sessions,
	// password store) and exposing it to a sandboxed chromium would be a
	// material confidentiality leak. The staging directories are fresh per
	// session and discarded when the staging HOME is cleaned up.
	//
	// MkdirAll is idempotent: if the directories already exist from a prior
	// re-spawn the call is a no-op and existing contents are preserved.
	if runtime.GOOS == "darwin" {
		chromeAppSupport := filepath.Join(stagingHome, "Library", "Application Support", "Google")
		chromeCaches := filepath.Join(stagingHome, "Library", "Caches", "Google")
		for _, d := range []string{chromeAppSupport, chromeCaches} {
			if err := os.MkdirAll(d, 0o700); err != nil {
				log.Printf("container: sandbox-exec: create chromium staging dir %s: %v", d, err)
			}
		}
	}

	// ── Library/Keychains/login.keychain-db — symlink for Keychain API ──────
	// On Darwin, opencode-claude-auth uses `security dump-keychain` and
	// `security find-generic-password` to retrieve Claude credentials from the
	// macOS Keychain. Both commands use $HOME to locate the keychain search
	// list, and inside the sandbox $HOME points at the staging directory. By
	// symlinking $stagingHome/Library/Keychains/login.keychain-db → the real
	// login.keychain-db, `security` finds the correct search list and can
	// retrieve credentials. The SBPL profile grants file-read* on the resolved
	// (real) path via the (literal login.keychain-db) rule (issue #1487).
	// Token refresh writes go through the `security add-generic-password`
	// Mach IPC path which is not affected by this symlink.
	if runtime.GOOS == "darwin" {
		realKeychain := filepath.Join(home, "Library", "Keychains", "login.keychain-db")
		if _, err := os.Stat(realKeychain); err == nil {
			keychainLink := filepath.Join(stagingHome, "Library", "Keychains", "login.keychain-db")
			if mkErr := os.MkdirAll(filepath.Dir(keychainLink), 0o755); mkErr == nil {
				_ = os.Symlink(realKeychain, keychainLink)
			}
		}
	}

	// ── .claude/ — symlink to host ~/.claude (RW write-through) ──────────────
	// opencode-claude-auth token refreshes write .credentials.json inside
	// ~/.claude/, and since this is a symlink to host ~/.claude, those writes
	// flow through to the host path and are immediately reflected in subsequent
	// sessions. On Linux, ~/.claude/.credentials.json already lives on disk;
	// the bwrap path bind-mounts ~/.claude/ with RW access (bwrap.go:306-308).
	symlinkIfExists(
		filepath.Join(home, ".claude"),
		filepath.Join(stagingHome, ".claude"),
	)

	// ── .mcp-auth/ ────────────────────────────────────────────────────────────
	symlinkIfExists(
		filepath.Join(home, ".mcp-auth"),
		filepath.Join(stagingHome, ".mcp-auth"),
	)

	// ── .npm/ ─────────────────────────────────────────────────────────────────
	// npx caches downloaded packages (e.g. mcp-remote) under ~/.npm/_npx/.
	// Without this symlink, npx cannot find its cache and attempts to re-download
	// packages, which fails due to network restrictions in the sandbox.
	symlinkIfExists(
		filepath.Join(home, ".npm"),
		filepath.Join(stagingHome, ".npm"),
	)

	// ── .cache/ ───────────────────────────────────────────────────────────────

	// bun cache — only linked when writable (mirrors bwrap.go:474-477).
	bunCacheDir := filepath.Join(home, ".cache", "bun")
	if isWritable(bunCacheDir) {
		symlinkIfExists(bunCacheDir, filepath.Join(stagingHome, ".cache", "bun"))
	}

	// nix cache — always included as RW symlink (matches bwrap.go:333-335,
	// unconditional RW bind of ~/.cache/nix).
	nixCacheDir := filepath.Join(home, ".cache", "nix")
	symlinkIfExists(nixCacheDir, filepath.Join(stagingHome, ".cache", "nix"))

	// prism clipboard cache — conditional on existence.
	clipboardCacheDir := filepath.Join(home, ".cache", "prism", "clipboard")
	if _, err := os.Stat(clipboardCacheDir); err == nil {
		// Create intermediate dir .cache/prism/ if needed.
		_ = os.MkdirAll(filepath.Join(stagingHome, ".cache", "prism"), 0o700)
		symlinkIfExists(clipboardCacheDir, filepath.Join(stagingHome, ".cache", "prism", "clipboard"))
	}

	// ── .gitconfig — regular generated file ──────────────────────────────────
	// Use the existing writeGitconfig helper with a synthetic isolationMode
	// that uses the staging HOME as $HOME. We write the gitconfig to the
	// staging path directly.
	//
	// A failure here is fatal — return the error so the session does not
	// start with a missing or broken gitconfig. Previously we logged and
	// continued, which is what let issue #1960 (missing [user] section →
	// synthetic in-sandbox identity → noisy Co-authored-by trailer) sneak
	// through unnoticed.
	if err := m.writeGitconfigToDir(stagingHome); err != nil {
		return "", fmt.Errorf("container: sandbox-exec: write staging .gitconfig: %w", err)
	}

	// ── .nix-profile symlink ──────────────────────────────────────────────────
	symlinkIfExists(
		filepath.Join(home, ".nix-profile"),
		filepath.Join(stagingHome, ".nix-profile"),
	)

	// ── PI Atlassian MCP OAuth token persistence (Darwin only) ───────────────
	// The Atlassian MCP extension stores OAuth tokens at
	// homedir()/.pi/agent/atlassian-mcp-oauth.json. On Darwin sandbox-exec,
	// $HOME inside the session is the per-session staging HOME, so writes to
	// that path land in the staging dir and are destroyed when the session
	// ends. To persist tokens across sessions we:
	//
	//  1. Create <stagingHome>/.pi/agent/ as a real directory (so the
	//     extension's mkdirSync({ recursive: true }) is a no-op).
	//  2. Touch ~/.pi/agent/atlassian-mcp-oauth.json on the host with mode
	//     0600 if absent — bwrap does the same in appendPIBwrapMounts.
	//  3. Symlink <stagingHome>/.pi/agent/atlassian-mcp-oauth.json to the
	//     real host path so reads and writes flow through to the host.
	//
	// The SBPL profile already emits
	//   (allow file-read* file-write* ... (subpath ~/.pi/agent))
	// for Harness == "pi" sessions, so no profile changes are required.
	//
	// The change is gated on BOTH runtime.GOOS == "darwin" AND
	// m.cfg.Harness == "pi" so that non-pi sessions are unaffected.
	if runtime.GOOS == "darwin" && m.cfg.Harness == "pi" {
		if err := m.stagePIOAuthToken(home, stagingHome); err != nil {
			log.Printf("container: sandbox-exec: stage PI OAuth token: %v", err)
		}
	}

	return stagingHome, nil
}

// stagePIOAuthToken creates the staging HOME infrastructure for the
// Atlassian MCP OAuth token under a pi harness Darwin session:
//
//  1. Creates <stagingHome>/.pi/agent/ as a real directory (mode 0700).
//  2. Ensures ~/.pi/agent/ exists on the host (mode 0700).
//  3. Touches ~/.pi/agent/atlassian-mcp-oauth.json on the host with
//     mode 0600 if absent (existing files are never modified).
//  4. Symlinks <stagingHome>/.pi/agent/atlassian-mcp-oauth.json →
//     ~/.pi/agent/atlassian-mcp-oauth.json (idempotent).
//
// This mirrors the bwrap touch-and-bind pattern in
// pi_invocation.go::appendPIBwrapMounts.
func (m *Manager) stagePIOAuthToken(home, stagingHome string) error {
	// 1. Create <stagingHome>/.pi/agent/ as a real directory.
	stagingAgentDir := filepath.Join(stagingHome, ".pi", "agent")
	if err := os.MkdirAll(stagingAgentDir, 0o700); err != nil {
		return fmt.Errorf("create staging .pi/agent dir %s: %w", stagingAgentDir, err)
	}

	// 2. Ensure ~/.pi/agent/ exists on the host.
	hostAgentDir := filepath.Join(home, ".pi", "agent")
	if err := os.MkdirAll(hostAgentDir, 0o700); err != nil {
		return fmt.Errorf("create host .pi/agent dir %s: %w", hostAgentDir, err)
	}

	// 3. Touch ~/.pi/agent/atlassian-mcp-oauth.json on the host if absent.
	// Use O_CREATE|O_EXCL so an existing file is never truncated or modified.
	hostTokenPath := filepath.Join(hostAgentDir, "atlassian-mcp-oauth.json")
	if _, statErr := os.Stat(hostTokenPath); os.IsNotExist(statErr) {
		f, createErr := os.OpenFile(hostTokenPath, os.O_CREATE|os.O_EXCL, 0o600)
		if createErr == nil {
			_ = f.Close()
		} else if !os.IsExist(createErr) {
			return fmt.Errorf("touch host token file %s: %w", hostTokenPath, createErr)
		}
	}

	// 4. Symlink <stagingHome>/.pi/agent/atlassian-mcp-oauth.json → host path.
	// Remove any existing entry first (file, symlink, or otherwise) so
	// the operation is idempotent.
	stagingTokenPath := filepath.Join(stagingAgentDir, "atlassian-mcp-oauth.json")
	_ = os.Remove(stagingTokenPath)
	if err := os.Symlink(hostTokenPath, stagingTokenPath); err != nil {
		return fmt.Errorf("symlink %s → %s: %w", stagingTokenPath, hostTokenPath, err)
	}
	return nil
}

// isWritable returns true when the path exists and is accessible for writing
// by the current process. A nil error from a writable-test os.OpenFile call
// indicates writeability; any error (including EACCES) returns false.
func isWritable(path string) bool {
	if _, err := os.Stat(path); err != nil {
		return false // doesn't exist
	}
	// Attempt to open a temp file inside the directory. This is the most
	// reliable way to test writeability without relying on access(2) (which
	// has TOCTOU issues and doesn't honour ACLs on all platforms).
	tmp, err := os.CreateTemp(path, ".prism-write-test-*")
	if err != nil {
		return false
	}
	_ = tmp.Close()
	_ = os.Remove(tmp.Name())
	return true
}

// writeSshConfigToDir writes a generated .ssh/config file into the given
// staging HOME directory. The IdentityFile path uses stagingHome as the
// in-sandbox $HOME prefix so it resolves correctly inside the sandbox.
func (m *Manager) writeSshConfigToDir(stagingHome string) error {
	identityFile := filepath.Join(stagingHome, ".ssh", "access-key")
	sshConfig := "Host github.com\n" +
		"  StrictHostKeyChecking accept-new\n" +
		"  IdentityFile " + identityFile + "\n" +
		"  IdentitiesOnly yes\n"
	dst := filepath.Join(stagingHome, ".ssh", "config")
	_ = os.Remove(dst) // idempotent
	if err := os.WriteFile(dst, []byte(sshConfig), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", dst, err)
	}
	return nil
}

// writeGitconfigToDir generates a .gitconfig and (when signing is available)
// allowed_signers for the sandbox-exec staging HOME. It is a thin wrapper
// around writeGitconfig(isolationSandboxExec) — the canonical helper used
// by podman and bwrap — and then materialises the resulting temp files into
// the staging HOME at the canonical paths the agent expects:
//
//	<stagingHome>/.gitconfig
//	<stagingHome>/.ssh/allowed_signers   (when signing is configured)
//
// The temp files written by writeGitconfig (m.gitconfigFilePath() and
// m.allowedSignersFilePath()) embed sandbox-relative paths derived from
// sandboxHome(m, isolationSandboxExec) — which resolves to stagingHome — so
// the file content is identical whether read from the temp path or from the
// staging HOME copy. We materialise into the staging HOME because
// sandbox-exec has no bind-mount mechanism: the agent reads the file
// directly from $HOME inside the sandbox.
func (m *Manager) writeGitconfigToDir(stagingHome string) error {
	if err := m.writeGitconfig(isolationSandboxExec); err != nil {
		return fmt.Errorf("write gitconfig: %w", err)
	}

	// Copy the generated gitconfig into the staging HOME at the canonical
	// path the agent expects (<stagingHome>/.gitconfig).
	gitconfigContent, err := os.ReadFile(m.gitconfigFilePath())
	if err != nil {
		return fmt.Errorf("read generated gitconfig %s: %w", m.gitconfigFilePath(), err)
	}
	gitconfigDst := filepath.Join(stagingHome, ".gitconfig")
	_ = os.Remove(gitconfigDst) // idempotent: replace any prior symlink/file
	if err := os.WriteFile(gitconfigDst, gitconfigContent, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", gitconfigDst, err)
	}

	// When writeGitconfig produced an allowed_signers file (i.e. signing is
	// configured and the public key was readable), copy it into the staging
	// HOME's .ssh directory so git verify-commit succeeds inside the sandbox.
	if m.allowedSignersReady {
		signersContent, readErr := os.ReadFile(m.allowedSignersFilePath())
		if readErr != nil {
			return fmt.Errorf("read generated allowed_signers %s: %w", m.allowedSignersFilePath(), readErr)
		}
		signersDst := filepath.Join(stagingHome, ".ssh", "allowed_signers")
		_ = os.Remove(signersDst) // idempotent: replace prior symlink/file
		if err := os.WriteFile(signersDst, signersContent, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", signersDst, err)
		}
	}

	return nil
}

// SandboxExecHomePath is the exported version of sandboxExecHomePath. It
// returns the staging HOME path for this Manager's session/instance. Used by
// cmd/agent_run.go to override HOME in the env passed to syscall.Exec.
func (m *Manager) SandboxExecHomePath() (string, error) {
	return m.sandboxExecHomePath()
}

// SandboxExecStagingHomePath returns the staging HOME path for the given
// instance ID. This is an exported convenience for callers (e.g. cmd/cleanup.go)
// that have the instance_id but no Manager instance.
//
// Path: ~/.local/state/prism/sessions/<instanceID>/home/
func SandboxExecStagingHomePath(instanceID string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}
	if home == "" {
		return "", fmt.Errorf("container: sandbox-exec: cannot determine user home directory")
	}
	if instanceID == "" {
		return "", fmt.Errorf("container: sandbox-exec: instanceID is empty")
	}
	return filepath.Join(home, ".local", "state", "prism", "sessions", instanceID, "home"), nil
}

// RemoveSandboxExecStagingHome removes the staging HOME directory tree for the
// given instance ID. It is idempotent — calling it when the directory does not
// exist is a no-op.
//
// This is called from cmd/cleanup.go cleanup paths that have the instance_id
// (e.g. headlessCleanup, headlessCloseSession) to clean up the staging dir
// created by PrepareSandboxExecHome.
func RemoveSandboxExecStagingHome(instanceID string) {
	stagingHome, err := SandboxExecStagingHomePath(instanceID)
	if err != nil {
		return // can't derive path — nothing to do
	}
	_ = os.RemoveAll(stagingHome)
}

// StagingSymlinkTarget represents a resolved symlink target with metadata
// about whether the target is a directory (requiring subpath) or a file
// (allowing literal), and whether writes to the target must be allowed.
type StagingSymlinkTarget struct {
	// ResolvedPath is the resolved absolute path of the symlink target.
	ResolvedPath string
	// IsDir is true when the resolved target is a directory. Directory
	// targets require (subpath ...) rules in SBPL; file targets use (literal ...).
	IsDir bool
	// Writable is true when the sandbox must be allowed to write to this
	// target (and, for directories, its contents). Mirrors the bwrap --bind
	// (RW) vs --ro-bind (RO) distinction:
	//   RW: .cache/opencode, .cache/bun, .cache/nix,
	//       .claude (write-through for credentials), .mcp-auth
	//   RO: .ssh keys, .aws staged entries, .kube/config, .config/opencode/*,
	//       .config/prism/agents (role prompts; issue #2032),
	//       .cache/prism/clipboard (read-only; mirrors bwrap.go --ro-bind)
	Writable bool
}

// collectStagingHomeSymlinkTargets resolves all symlinks in the staging HOME
// directory and returns the unique set of resolved real paths. These are the
// paths the SBPL profile must allow so the sandbox can read through the symlinks.
//
// The return value includes IsDir and Writable metadata so callers can emit
// the appropriate SBPL rules:
//   - Directory targets → (subpath ...) rules.
//   - File targets → (literal ...) rules.
//   - Writable targets (cache dirs, write-through credential dirs) → file-write*
//     alongside file-read*; RO targets → file-read* only.
//
// Writable classification mirrors the bwrap --bind (RW) vs --ro-bind (RO)
// distinction from bwrap.go. The following staging HOME paths are treated as
// writable, consistent with how PrepareSandboxExecHome populates them:
//   - .cache/opencode  — opencode refreshes models.json and writes bin/ shims
//   - .cache/bun       — bun writes transpile outputs and lockfile updates
//   - .cache/nix       — unconditional RW (mirrors bwrap.go:333-335)
//   - .claude          — write-through for .credentials.json on Darwin
//   - .mcp-auth        — MCP auth token writes
//
// All other targets (.ssh, .aws, .kube, .config/opencode, .cache/prism/clipboard)
// are read-only. .cache/prism/clipboard mirrors bwrap.go's --ro-bind treatment —
// the agent only reads image files staged there by `prism clipboard paste-image`.
//
// Symlink targets that fall under a path that will be denied by the profile
// (e.g. host $HOME/.aws) are excluded from the results to avoid the
// literal-over-subpath precedence issue in Apple's SBPL: a (literal ...) allow
// for a path inside a (subpath ...) deny region would defeat the deny.
//
// The traversal is shallow: only top-level symlinks in the staging HOME tree
// are followed. We do not recurse into symlinked directory contents.
func collectStagingHomeSymlinkTargets(stagingHome string) ([]StagingSymlinkTarget, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}

	// deniedPrefixes lists host paths that will be denied in the SBPL profile.
	// Symlink targets that fall under these prefixes are excluded from the
	// allow-literal/subpath block to avoid the literal-over-subpath precedence
	// issue in Apple's SBPL.
	//
	// allowedUnderDenied lists specific sub-paths that are carved out of the
	// denied region. generateProfile emits explicit (allow file-read* (subpath
	// ...)) rules for these after the broad deny, so it is safe for the
	// per-symlink allow block to reference their targets.
	// Concretely: ~/.aws/sso and ~/.aws/cli are carved out so that the staging
	// HOME symlinks for those dirs produce per-symlink allow rules.
	var deniedPrefixes []string
	var allowedUnderDenied []string
	if home != "" {
		deniedPrefixes = append(deniedPrefixes, filepath.Join(home, ".aws")+"/")
		// Carve sso/ and cli/ out of the denied region — generateProfile emits
		// explicit (allow file-read* (subpath ~/.aws/sso)) and
		// (allow file-read* (subpath ~/.aws/cli)) after the broad deny.
		allowedUnderDenied = append(allowedUnderDenied,
			filepath.Join(home, ".aws", "sso")+"/",
			filepath.Join(home, ".aws", "cli")+"/",
		)
	}

	isDenied := func(path string) bool {
		// Check whether the path falls under any allowed carve-out first.
		// If yes, it is not considered denied even if a broader deny prefix matches.
		for _, allowed := range allowedUnderDenied {
			if strings.HasPrefix(path+"/", allowed) || path == strings.TrimSuffix(allowed, "/") {
				return false
			}
		}
		for _, prefix := range deniedPrefixes {
			if strings.HasPrefix(path+"/", prefix) || path == strings.TrimSuffix(prefix, "/") {
				return true
			}
		}
		return false
	}

	// writableStagingPaths is the set of staging HOME paths whose symlink
	// targets must be granted write access in the SBPL profile. Keyed by the
	// path relative to stagingHome (no leading slash). Matches the RW paths
	// in PrepareSandboxExecHome and the bwrap --bind mounts in bwrap.go.
	writableStagingPaths := map[string]bool{
		".cache/bun": true, // bun transpile cache + lockfile
		".cache/nix": true, // nix eval cache (unconditional RW)
		// .cache/prism/clipboard is intentionally absent: agents only read
		// images staged there; mirrors bwrap.go's --ro-bind treatment.
		".claude":   true, // write-through for .credentials.json
		".mcp-auth": true, // MCP auth token writes
		".npm":      true, // npx package cache (mcp-remote et al.)
		// AWS SSO and CLI cache dirs must be writable so the aws CLI can write
		// STS token cache entries (~/.aws/cli/cache/) and refresh SSO tokens
		// (~/.aws/sso/). Without write access the CLI gets EPERM and kubectl
		// against EKS also fails (its exec-credential plugin shells out to aws).
		// Mirrors bwrap's --bind (RW) treatment — awsSSOReadOnly/awsCLIReadOnly
		// are both false in mounts.go (issue #1558).
		".aws/sso": true, // AWS SSO token refresh writes
		".aws/cli": true, // AWS CLI STS token cache writes
	}

	seen := map[string]bool{}
	var targets []StagingSymlinkTarget

	// add resolves a symlink's raw target (the value of os.Readlink) and
	// appends it to targets. entryRelPath is the path of the symlink entry
	// relative to stagingHome, used to look up the Writable classification.
	add := func(rawTarget, entryRelPath string) {
		resolved, evalErr := filepath.EvalSymlinks(rawTarget)
		if evalErr != nil {
			return
		}
		if seen[resolved] {
			return
		}
		if isDenied(resolved) {
			// Exclude targets under denied paths to avoid defeating deny rules.
			return
		}
		seen[resolved] = true
		// Determine whether the target is a directory or a file.
		info, statErr := os.Stat(resolved)
		isDir := statErr == nil && info.IsDir()
		writable := writableStagingPaths[entryRelPath]
		targets = append(targets, StagingSymlinkTarget{
			ResolvedPath: resolved,
			IsDir:        isDir,
			Writable:     writable,
		})
	}

	// Use os.ReadDir for the top-level staging HOME entries only (no recursion).
	// filepath.Walk doesn't follow symlinks, so a top-level walk would stop at
	// symlinks pointing at directories — which is the behaviour we want (don't
	// recurse into symlinked dirs). We use ReadDir instead for clarity.
	scanDir := func(dirRelPath string) {
		dir := filepath.Join(stagingHome, dirRelPath)
		entries, readErr := os.ReadDir(dir)
		if readErr != nil {
			return
		}
		for _, e := range entries {
			entryPath := filepath.Join(dir, e.Name())
			// Only process symlinks; regular files and real dirs are fine as-is.
			if e.Type()&os.ModeSymlink != 0 {
				linkTarget, readLinkErr := os.Readlink(entryPath)
				if readLinkErr != nil {
					continue
				}
				if !filepath.IsAbs(linkTarget) {
					linkTarget = filepath.Join(dir, linkTarget)
				}
				// Compute entry path relative to stagingHome for writable lookup.
				var relPath string
				if dirRelPath == "" {
					relPath = e.Name()
				} else {
					relPath = dirRelPath + "/" + e.Name()
				}
				add(linkTarget, relPath)
			}
		}
	}

	// Scan the top-level staging HOME and all immediate subdirectories that
	// the staging HOME builder creates (one level deep).
	scanDir("")
	subDirs := []string{".ssh", ".aws", ".kube", ".cache", ".pi"}
	for _, sub := range subDirs {
		scanDir(sub)
	}
	// Also scan .cache/prism if it exists.
	scanDir(".cache/prism")
	// Scan .config/prism for the prism/agents role-prompt symlink (issue #2032).
	scanDir(".config/prism")

	return targets, nil
}
