package container

// sandbox_exec_home.go — per-session staging HOME builder for sandbox-exec mode.
//
// PrepareSandboxExecHome populates a staging HOME directory at
// ~/.local/state/prism/sessions/<instance_id>/home/ with symlinks to the real
// credential, config, and cache paths opencode needs. The SBPL profile grants
// read access to every resolved symlink target, while the staging HOME itself
// is writable so the sandbox can do things like write to ~/.cache/opencode
// inside it (which symlinks through to the host path).
//
// Design decisions locked by the coordinator in issue #1017:
//
//  1. .claude/ is a symlink to host ~/.claude (matches bwrap's RW treatment at
//     bwrap.go:306-308). On Darwin this means writeClaudeCredentials() extracts
//     to its existing temp path, and the file is reachable inside the sandbox
//     at $HOME/.claude/.credentials.json via the symlink. On Darwin, writes to
//     .credentials.json flow through the symlink to the host's ~/.claude/.credentials.json.
//     This is the accepted trade-off (simplest, matches bwrap's RW treatment).
//
//  2. .config/opencode/agents/ is role-conditional: included as a symlink for
//     non-review roles, omitted for review-prefixed roles. Mirrors bwrap.go:447-448.
//
//  3. .cache/nix/ is included as an RW symlink to ~/.cache/nix (matches bwrap
//     unconditional RW bind at bwrap.go:333-335).

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// sandboxExecHomePath returns the staging HOME path for the given instance ID.
// The path is:
//
//	~/.local/state/prism/sessions/<instance_id>/home/
//
// This is the per-session staging HOME that PrepareSandboxExecHome creates and
// populates with symlinks. InstanceID is used as the namespace key so concurrent
// sessions have independent staging dirs.
func (m *Manager) sandboxExecHomePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}
	if home == "" {
		return "", fmt.Errorf("container: sandbox-exec: cannot determine user home directory")
	}
	instanceID := m.cfg.InstanceID
	if instanceID == "" {
		// Fall back to session name when InstanceID is not set (e.g. tests
		// that construct Manager directly without a full spawn lifecycle).
		// Use the container name (slugified session name) to stay safe for
		// filesystem use.
		instanceID = m.name
	}
	return filepath.Join(home, ".local", "state", "prism", "sessions", instanceID, "home"), nil
}

// PrepareSandboxExecHome creates the per-session staging HOME directory and
// populates it with symlinks to the real credential, config, and cache paths
// that opencode needs. Returns the absolute path to the staging HOME.
//
// The staging HOME layout mirrors the bwrap sandbox home layout (every path
// that bwrap creates via bind-mount, sandbox-exec achieves via a symlink). The
// SBPL profile generated by generateProfile grants read access to every resolved
// symlink target so the sandbox can traverse the symlinks.
//
// Rules:
//   - When a source path does not exist on the host, the symlink is skipped.
//     No dangling symlinks are created.
//   - Generated regular files (.gitconfig, .ssh/config, opencode.json) are
//     written as regular files, not symlinks.
//   - .cache/nix/ is always included as an RW symlink to ~/.cache/nix.
//   - .config/opencode/agents/ is only included when AgentRole does NOT start
//     with "review-" (mirrors bwrap.go:447-448).
//   - .claude/ is a symlink to host ~/.claude with a comment explaining the
//     Darwin write-through behaviour.
//
// Calling PrepareSandboxExecHome a second time on an existing staging dir is
// idempotent: existing symlinks are recreated (os.Symlink is preceded by
// os.Remove) and regular files are overwritten.
func (m *Manager) PrepareSandboxExecHome() (string, error) {
	stagingHome, err := m.sandboxExecHomePath()
	if err != nil {
		return "", err
	}

	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}

	// ── Create the staging HOME directory tree ────────────────────────────────
	// All subdirectories that will receive symlinks or generated files must
	// be created before we attempt to create entries inside them.
	dirs := []string{
		stagingHome,
		filepath.Join(stagingHome, ".ssh"),
		filepath.Join(stagingHome, ".aws"),
		filepath.Join(stagingHome, ".kube"),
		filepath.Join(stagingHome, ".config", "opencode"),
		filepath.Join(stagingHome, ".cache"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0o700); err != nil {
			return "", fmt.Errorf("container: sandbox-exec: create staging dir %s: %w", d, err)
		}
	}

	// ── Helper: create a symlink (idempotent) ─────────────────────────────────
	// Removes any existing entry at dst (file, symlink, or empty dir) before
	// creating the new symlink so that re-runs are idempotent.
	makeSymlink := func(src, dst string) error {
		_ = os.Remove(dst) // ignore error — may not exist
		return os.Symlink(src, dst)
	}

	// ── Helper: conditionally create symlink if source exists (os.Stat) ──────
	symlinkIfExists := func(src, dst string) {
		if _, err := os.Stat(src); err != nil {
			return // source does not exist — skip; no dangling symlinks
		}
		if err := makeSymlink(src, dst); err != nil {
			log.Printf("container: sandbox-exec: symlink %s → %s: %v", dst, src, err)
		}
	}

	// ── Helper: conditionally create symlink if EvalSymlinks succeeds ────────
	// Used for paths where symlink resolution is required (e.g. Nix store
	// paths that are themselves symlinks). The symlink points at the resolved
	// real path so the SBPL profile can allow that literal path.
	symlinkIfResolvable := func(src, dst string) (resolvedSrc string) {
		resolved, err := filepath.EvalSymlinks(src)
		if err != nil {
			return "" // source does not resolve — skip
		}
		if err := makeSymlink(resolved, dst); err != nil {
			log.Printf("container: sandbox-exec: symlink %s → %s: %v", dst, resolved, err)
			return ""
		}
		return resolved
	}

	// ── SSH keys ──────────────────────────────────────────────────────────────
	// Mirror bwrap.go:369-388: resolve via EvalSymlinks and mount at generic
	// canonical names under $HOME/.ssh/.
	sshDir := filepath.Join(home, ".ssh")

	accessKeyName := m.cfg.SshAccessKeyName
	if accessKeyName == "" {
		accessKeyName = "prismatic-koi-ed25519"
	}
	symlinkIfResolvable(
		filepath.Join(sshDir, accessKeyName),
		filepath.Join(stagingHome, ".ssh", "access-key"),
	)

	signingKeyName := m.cfg.SshSigningKeyName
	if signingKeyName == "" {
		signingKeyName = "prismatic-koi-ed25519-signingkey"
	}
	symlinkIfResolvable(
		filepath.Join(sshDir, signingKeyName),
		filepath.Join(stagingHome, ".ssh", "signing-key"),
	)
	symlinkIfResolvable(
		filepath.Join(sshDir, signingKeyName+".pub"),
		filepath.Join(stagingHome, ".ssh", "signing-key.pub"),
	)
	symlinkIfExists(
		filepath.Join(sshDir, "known_hosts"),
		filepath.Join(stagingHome, ".ssh", "known_hosts"),
	)
	symlinkIfExists(
		filepath.Join(sshDir, "allowed_signers"),
		filepath.Join(stagingHome, ".ssh", "allowed_signers"),
	)

	// .ssh/config — regular generated file (not a symlink), using staging HOME
	// as the in-sandbox $HOME prefix so IdentityFile resolves correctly.
	if err := m.writeSshConfigToDir(stagingHome); err != nil {
		log.Printf("container: sandbox-exec: write staging .ssh/config: %v", err)
	}

	// ── AWS ───────────────────────────────────────────────────────────────────
	// Match bwrap.go pattern: resolve ~/.config/aws/readonly-config and
	// ~/.config/aws/credentials via EvalSymlinks; mount ~/.aws/sso and
	// ~/.aws/cli via os.Stat.
	symlinkIfResolvable(
		filepath.Join(home, ".config", "aws", "readonly-config"),
		filepath.Join(stagingHome, ".aws", "config"),
	)
	symlinkIfResolvable(
		filepath.Join(home, ".config", "aws", "credentials"),
		filepath.Join(stagingHome, ".aws", "credentials"),
	)
	symlinkIfExists(
		filepath.Join(home, ".aws", "sso"),
		filepath.Join(stagingHome, ".aws", "sso"),
	)
	symlinkIfExists(
		filepath.Join(home, ".aws", "cli"),
		filepath.Join(stagingHome, ".aws", "cli"),
	)

	// ── Kube ──────────────────────────────────────────────────────────────────
	symlinkIfResolvable(
		filepath.Join(home, ".config", "kube", "agents-config"),
		filepath.Join(stagingHome, ".kube", "config"),
	)

	// ── .claude/ — symlink to host ~/.claude (RW write-through) ──────────────
	// On Darwin, opencode-claude-auth writes .credentials.json inside
	// ~/.claude/. Since this is a symlink to host ~/.claude, writes inside
	// the sandbox flow through to the host's ~/.claude/.credentials.json.
	// This is the accepted trade-off: simplest, matches bwrap's RW bind of
	// ~/.claude at bwrap.go:306-308. On Linux, ~/.claude/.credentials.json
	// already lives there; no Keychain extraction is needed.
	// Darwin-specific: writeClaudeCredentials() below extracts from Keychain
	// to a temp path (m.claudeCredentialsFilePath()), which is reachable at
	// $HOME/.claude/.credentials.json via this symlink (because the temp path
	// equals the host's ~/.claude/.credentials.json location via write-through).
	symlinkIfExists(
		filepath.Join(home, ".claude"),
		filepath.Join(stagingHome, ".claude"),
	)

	// ── .mcp-auth/ ────────────────────────────────────────────────────────────
	symlinkIfExists(
		filepath.Join(home, ".mcp-auth"),
		filepath.Join(stagingHome, ".mcp-auth"),
	)

	// ── .config/opencode/ ─────────────────────────────────────────────────────
	// Mirror bwrap.go:438-455 allowlist. opencode.json is a generated regular
	// file (written below), not a symlink.
	opencodeConfigDir := filepath.Join(home, ".config", "opencode")
	opencodeAllowlist := []string{
		"AGENTS.md",
		"plugins",
		"skills",
		"command",
		"tui.json",
		".gitignore",
		"mcp-atlassian-slim-proxy.mjs",
		// node_modules and bun.lock are included so that bun finds the
		// pre-installed plugin packages without running `bun install` from
		// scratch on every session. In bwrap, the host ~/.config/opencode dir
		// is bind-mounted so node_modules is implicitly available; in sandbox-exec
		// the staging .config/opencode is a fresh directory built from this
		// allowlist, so without these entries bun re-downloads and re-installs
		// every plugin on cold start (~8s per session).
		"node_modules",
		"bun.lock",
	}
	// agents/ is role-conditional: mirror bwrap.go:447-448.
	if !strings.HasPrefix(m.cfg.AgentRole, "review-") {
		opencodeAllowlist = append(opencodeAllowlist, "agents")
	}
	for _, entry := range opencodeAllowlist {
		src := filepath.Join(opencodeConfigDir, entry)
		dst := filepath.Join(stagingHome, ".config", "opencode", entry)
		symlinkIfExists(src, dst)
	}

	// opencode.json — regular generated file (not a symlink). Written from
	// the temp file path (m.opencodeConfigFilePath()) when that file exists.
	// The check is file-existence-based so files written at spawn time by
	// cmd/spawn.go are picked up even when ConfigContent is not in memory
	// (mirrors bwrap.go:419-422).
	opencodeConfigPath := m.opencodeConfigFilePath()
	if _, err := os.Stat(opencodeConfigPath); err == nil {
		content, readErr := os.ReadFile(opencodeConfigPath)
		if readErr == nil {
			dstConfig := filepath.Join(stagingHome, ".config", "opencode", "opencode.json")
			_ = os.Remove(dstConfig) // idempotent
			if writeErr := os.WriteFile(dstConfig, content, 0o644); writeErr != nil {
				log.Printf("container: sandbox-exec: write staging opencode.json: %v", writeErr)
			}
		}
	}

	// ── .cache/ ───────────────────────────────────────────────────────────────
	// opencode cache — only linked when writable (mirrors bwrap.go:464-467).
	opencodeCacheDir := filepath.Join(home, ".cache", "opencode")
	if isWritable(opencodeCacheDir) {
		symlinkIfExists(opencodeCacheDir, filepath.Join(stagingHome, ".cache", "opencode"))
	}

	// bun cache — only linked when writable (mirrors bwrap.go:474-477).
	bunCacheDir := filepath.Join(home, ".cache", "bun")
	if isWritable(bunCacheDir) {
		symlinkIfExists(bunCacheDir, filepath.Join(stagingHome, ".cache", "bun"))
	}

	// nix cache — always included as RW symlink (matches bwrap.go:333-335,
	// unconditional RW bind of ~/.cache/nix).
	nixCacheDir := filepath.Join(home, ".cache", "nix")
	symlinkIfExists(nixCacheDir, filepath.Join(stagingHome, ".cache", "nix"))

	// prism clipboard cache — conditional on existence.
	clipboardCacheDir := filepath.Join(home, ".cache", "prism", "clipboard")
	if _, err := os.Stat(clipboardCacheDir); err == nil {
		// Create intermediate dir .cache/prism/ if needed.
		_ = os.MkdirAll(filepath.Join(stagingHome, ".cache", "prism"), 0o700)
		symlinkIfExists(clipboardCacheDir, filepath.Join(stagingHome, ".cache", "prism", "clipboard"))
	}

	// ── .gitconfig — regular generated file ──────────────────────────────────
	// Use the existing writeGitconfig helper with a synthetic isolationMode
	// that uses the staging HOME as $HOME. We write the gitconfig to the
	// staging path directly.
	if err := m.writeGitconfigToDir(stagingHome); err != nil {
		log.Printf("container: sandbox-exec: write staging .gitconfig: %v", err)
	}

	// ── .nix-profile symlink ──────────────────────────────────────────────────
	symlinkIfExists(
		filepath.Join(home, ".nix-profile"),
		filepath.Join(stagingHome, ".nix-profile"),
	)

	return stagingHome, nil
}

// isWritable returns true when the path exists and is accessible for writing
// by the current process. A nil error from a writable-test os.OpenFile call
// indicates writeability; any error (including EACCES) returns false.
func isWritable(path string) bool {
	if _, err := os.Stat(path); err != nil {
		return false // doesn't exist
	}
	// Attempt to open a temp file inside the directory. This is the most
	// reliable way to test writeability without relying on access(2) (which
	// has TOCTOU issues and doesn't honour ACLs on all platforms).
	tmp, err := os.CreateTemp(path, ".prism-write-test-*")
	if err != nil {
		return false
	}
	_ = tmp.Close()
	_ = os.Remove(tmp.Name())
	return true
}

// writeSshConfigToDir writes a generated .ssh/config file into the given
// staging HOME directory. The IdentityFile path uses stagingHome as the
// in-sandbox $HOME prefix so it resolves correctly inside the sandbox.
func (m *Manager) writeSshConfigToDir(stagingHome string) error {
	identityFile := filepath.Join(stagingHome, ".ssh", "access-key")
	sshConfig := "Host github.com\n" +
		"  StrictHostKeyChecking accept-new\n" +
		"  IdentityFile " + identityFile + "\n" +
		"  IdentitiesOnly yes\n"
	dst := filepath.Join(stagingHome, ".ssh", "config")
	_ = os.Remove(dst) // idempotent
	if err := os.WriteFile(dst, []byte(sshConfig), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", dst, err)
	}
	return nil
}

// writeGitconfigToDir writes a generated .gitconfig file into the given
// staging HOME directory. It reuses the existing writeGitconfig logic but
// substitutes stagingHome as the in-sandbox $HOME so signingKey and
// allowedSignersFile paths resolve correctly inside the sandbox.
func (m *Manager) writeGitconfigToDir(stagingHome string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}
	sshDir := filepath.Join(home, ".ssh")

	signingKeyName := m.cfg.SshSigningKeyName
	if signingKeyName == "" {
		signingKeyName = "prismatic-koi-ed25519-signingkey"
	}
	signingKeyPriv := filepath.Join(sshDir, signingKeyName)
	signingKeyPub := filepath.Join(sshDir, signingKeyName+".pub")
	_, errPriv := filepath.EvalSymlinks(signingKeyPriv)
	_, errPub := filepath.EvalSymlinks(signingKeyPub)
	hasSigning := errPriv == nil && errPub == nil

	// The staging HOME's .ssh/ paths are what the agent will see inside the
	// sandbox. The gitconfig must reference those canonical generic names.
	sandboxSshDir := filepath.Join(stagingHome, ".ssh")
	sandboxSigningKeyPub := filepath.Join(sandboxSshDir, "signing-key.pub")
	sandboxAllowedSigners := filepath.Join(sandboxSshDir, "allowed_signers")

	var sb strings.Builder

	if m.cfg.GitUserName != "" && m.cfg.GitUserEmail != "" {
		sb.WriteString("[user]\n")
		sb.WriteString("    name = " + m.cfg.GitUserName + "\n")
		sb.WriteString("    email = " + m.cfg.GitUserEmail + "\n")
		if hasSigning {
			sb.WriteString("    signingKey = " + sandboxSigningKeyPub + "\n")
		}
	}

	if hasSigning && m.cfg.GitUserName != "" && m.cfg.GitUserEmail != "" {
		pubKeyContent, readErr := os.ReadFile(signingKeyPub)
		if readErr == nil {
			allowedSignersContent := m.cfg.GitUserEmail + " " + strings.TrimSpace(string(pubKeyContent)) + "\n"
			allowedSignersDst := filepath.Join(stagingHome, ".ssh", "allowed_signers")
			// Write the generated allowed_signers file (replaces any existing symlink).
			_ = os.Remove(allowedSignersDst)
			if writeErr := os.WriteFile(allowedSignersDst, []byte(allowedSignersContent), 0o644); writeErr == nil {
				sb.WriteString("\n[commit]\n")
				sb.WriteString("    gpgsign = true\n")
				sb.WriteString("\n[gpg]\n")
				sb.WriteString("    format = ssh\n")
				sb.WriteString("\n[gpg \"ssh\"]\n")
				sb.WriteString("    allowedSignersFile = " + sandboxAllowedSigners + "\n")
			}
		}
	}

	sb.WriteString("\n[push]\n")
	sb.WriteString("    autoSetupRemote = true\n")
	sb.WriteString("\n[init]\n")
	sb.WriteString("    defaultBranch = main\n")

	dst := filepath.Join(stagingHome, ".gitconfig")
	_ = os.Remove(dst) // idempotent
	if err := os.WriteFile(dst, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", dst, err)
	}
	return nil
}

// SandboxExecHomePath is the exported version of sandboxExecHomePath. It
// returns the staging HOME path for this Manager's session/instance. Used by
// cmd/agent_run.go to override HOME in the env passed to syscall.Exec.
func (m *Manager) SandboxExecHomePath() (string, error) {
	return m.sandboxExecHomePath()
}

// SandboxExecStagingHomePath returns the staging HOME path for the given
// instance ID. This is an exported convenience for callers (e.g. cmd/cleanup.go)
// that have the instance_id but no Manager instance.
//
// Path: ~/.local/state/prism/sessions/<instanceID>/home/
func SandboxExecStagingHomePath(instanceID string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}
	if home == "" {
		return "", fmt.Errorf("container: sandbox-exec: cannot determine user home directory")
	}
	if instanceID == "" {
		return "", fmt.Errorf("container: sandbox-exec: instanceID is empty")
	}
	return filepath.Join(home, ".local", "state", "prism", "sessions", instanceID, "home"), nil
}

// RemoveSandboxExecStagingHome removes the staging HOME directory tree for the
// given instance ID. It is idempotent — calling it when the directory does not
// exist is a no-op.
//
// This is called from cmd/cleanup.go cleanup paths that have the instance_id
// (e.g. headlessCleanup, headlessCloseSession) to clean up the staging dir
// created by PrepareSandboxExecHome.
func RemoveSandboxExecStagingHome(instanceID string) {
	stagingHome, err := SandboxExecStagingHomePath(instanceID)
	if err != nil {
		return // can't derive path — nothing to do
	}
	_ = os.RemoveAll(stagingHome)
}

// StagingSymlinkTarget represents a resolved symlink target with metadata
// about whether the target is a directory (requiring subpath) or a file
// (allowing literal), and whether writes to the target must be allowed.
type StagingSymlinkTarget struct {
	// ResolvedPath is the resolved absolute path of the symlink target.
	ResolvedPath string
	// IsDir is true when the resolved target is a directory. Directory
	// targets require (subpath ...) rules in SBPL; file targets use (literal ...).
	IsDir bool
	// Writable is true when the sandbox must be allowed to write to this
	// target (and, for directories, its contents). Mirrors the bwrap --bind
	// (RW) vs --ro-bind (RO) distinction:
	//   RW: .cache/opencode, .cache/bun, .cache/nix,
	//       .claude (write-through for credentials), .mcp-auth
	//   RO: .ssh keys, .aws staged entries, .kube/config, .config/opencode/*,
	//       .cache/prism/clipboard (read-only; mirrors bwrap.go --ro-bind)
	Writable bool
}

// collectStagingHomeSymlinkTargets resolves all symlinks in the staging HOME
// directory and returns the unique set of resolved real paths. These are the
// paths the SBPL profile must allow so the sandbox can read through the symlinks.
//
// The return value includes IsDir and Writable metadata so callers can emit
// the appropriate SBPL rules:
//   - Directory targets → (subpath ...) rules.
//   - File targets → (literal ...) rules.
//   - Writable targets (cache dirs, write-through credential dirs) → file-write*
//     alongside file-read*; RO targets → file-read* only.
//
// Writable classification mirrors the bwrap --bind (RW) vs --ro-bind (RO)
// distinction from bwrap.go. The following staging HOME paths are treated as
// writable, consistent with how PrepareSandboxExecHome populates them:
//   - .cache/opencode  — opencode refreshes models.json and writes bin/ shims
//   - .cache/bun       — bun writes transpile outputs and lockfile updates
//   - .cache/nix       — unconditional RW (mirrors bwrap.go:333-335)
//   - .claude          — write-through for .credentials.json on Darwin
//   - .mcp-auth        — MCP auth token writes
//
// All other targets (.ssh, .aws, .kube, .config/opencode, .cache/prism/clipboard)
// are read-only. .cache/prism/clipboard mirrors bwrap.go's --ro-bind treatment —
// opencode only reads image files staged there by `prism clipboard paste-image`.
//
// Symlink targets that fall under a path that will be denied by the profile
// (e.g. host $HOME/.aws) are excluded from the results to avoid the
// literal-over-subpath precedence issue in Apple's SBPL: a (literal ...) allow
// for a path inside a (subpath ...) deny region would defeat the deny.
//
// The traversal is shallow: only top-level symlinks in the staging HOME tree
// are followed. We do not recurse into symlinked directory contents.
func collectStagingHomeSymlinkTargets(stagingHome string) ([]StagingSymlinkTarget, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		home = os.Getenv("HOME")
	}

	// deniedPrefixes lists host paths that will be denied in the SBPL profile.
	// Symlink targets that fall under these prefixes are excluded from the
	// allow-literal/subpath block to avoid the literal-over-subpath precedence
	// issue in Apple's SBPL.
	var deniedPrefixes []string
	if home != "" {
		deniedPrefixes = append(deniedPrefixes, filepath.Join(home, ".aws")+"/")
	}

	isDenied := func(path string) bool {
		for _, prefix := range deniedPrefixes {
			if strings.HasPrefix(path+"/", prefix) || path == strings.TrimSuffix(prefix, "/") {
				return true
			}
		}
		return false
	}

	// writableStagingPaths is the set of staging HOME paths whose symlink
	// targets must be granted write access in the SBPL profile. Keyed by the
	// path relative to stagingHome (no leading slash). Matches the RW paths
	// in PrepareSandboxExecHome and the bwrap --bind mounts in bwrap.go.
	writableStagingPaths := map[string]bool{
		".cache/opencode":               true, // opencode models.json refresh + bin/ shims
		".cache/bun":                    true, // bun transpile cache + lockfile
		".cache/nix":                    true, // nix eval cache (unconditional RW)
		// .cache/prism/clipboard is intentionally absent: opencode only reads
		// images staged there; mirrors bwrap.go's --ro-bind treatment.
		".claude":                       true, // write-through for .credentials.json
		".mcp-auth":                     true, // MCP auth token writes
		".config/opencode/node_modules": true, // bun may update lockfile entries during plugin load
	}

	seen := map[string]bool{}
	var targets []StagingSymlinkTarget

	// add resolves a symlink's raw target (the value of os.Readlink) and
	// appends it to targets. entryRelPath is the path of the symlink entry
	// relative to stagingHome, used to look up the Writable classification.
	add := func(rawTarget, entryRelPath string) {
		resolved, evalErr := filepath.EvalSymlinks(rawTarget)
		if evalErr != nil {
			return
		}
		if seen[resolved] {
			return
		}
		if isDenied(resolved) {
			// Exclude targets under denied paths to avoid defeating deny rules.
			return
		}
		seen[resolved] = true
		// Determine whether the target is a directory or a file.
		info, statErr := os.Stat(resolved)
		isDir := statErr == nil && info.IsDir()
		writable := writableStagingPaths[entryRelPath]
		targets = append(targets, StagingSymlinkTarget{
			ResolvedPath: resolved,
			IsDir:        isDir,
			Writable:     writable,
		})
	}

	// Use os.ReadDir for the top-level staging HOME entries only (no recursion).
	// filepath.Walk doesn't follow symlinks, so a top-level walk would stop at
	// symlinks pointing at directories — which is the behaviour we want (don't
	// recurse into symlinked dirs). We use ReadDir instead for clarity.
	scanDir := func(dirRelPath string) {
		dir := filepath.Join(stagingHome, dirRelPath)
		entries, readErr := os.ReadDir(dir)
		if readErr != nil {
			return
		}
		for _, e := range entries {
			entryPath := filepath.Join(dir, e.Name())
			// Only process symlinks; regular files and real dirs are fine as-is.
			if e.Type()&os.ModeSymlink != 0 {
				linkTarget, readLinkErr := os.Readlink(entryPath)
				if readLinkErr != nil {
					continue
				}
				if !filepath.IsAbs(linkTarget) {
					linkTarget = filepath.Join(dir, linkTarget)
				}
				// Compute entry path relative to stagingHome for writable lookup.
				var relPath string
				if dirRelPath == "" {
					relPath = e.Name()
				} else {
					relPath = dirRelPath + "/" + e.Name()
				}
				add(linkTarget, relPath)
			}
		}
	}

	// Scan the top-level staging HOME and all immediate subdirectories that
	// the staging HOME builder creates (one level deep).
	scanDir("")
	subDirs := []string{".ssh", ".aws", ".kube", ".config/opencode", ".cache"}
	for _, sub := range subDirs {
		scanDir(sub)
	}
	// Also scan .cache/prism if it exists.
	scanDir(".cache/prism")

	return targets, nil
}
